<?php
@raise_memory_limit('496M');
@ini_set('max_execution_time','3000');
print "Loading data for table 'org'<br>";
$items = array(array('id' => '1','fullname' => 'Northland District Office','shortname' => 'Northland DO','description' => '','idnumber' => '1','frameworkid' => '1','path' => '/21/1','depthid' => '2','parentid' => '21','sortorder' => '2','visible' => '1','timecreated' => '0','timemodified' => '1267684145','usermodified' => '2',),
array('id' => '2','fullname' => 'Auckland District Office','shortname' => 'Auckland DO','description' => '','idnumber' => '2','frameworkid' => '1','path' => '/21/2','depthid' => '2','parentid' => '21','sortorder' => '7','visible' => '1','timecreated' => '0','timemodified' => '1267683923','usermodified' => '2',),
array('id' => '3','fullname' => 'Waikato District Office','shortname' => 'Waikato DO','description' => '','idnumber' => '3','frameworkid' => '1','path' => '/21/3','depthid' => '2','parentid' => '21','sortorder' => '11','visible' => '1','timecreated' => '0','timemodified' => '1267684122','usermodified' => '2',),
array('id' => '4','fullname' => 'East Coast Bay of Plenty District Office','shortname' => 'East Coast Bay of Plenty DO','description' => '','idnumber' => '4','frameworkid' => '1','path' => '/21/4','depthid' => '2','parentid' => '21','sortorder' => '15','visible' => '1','timecreated' => '0','timemodified' => '1267684098','usermodified' => '2',),
array('id' => '6','fullname' => 'Tongariro Taupo District Office','shortname' => 'Tongariro Taupo DO','description' => '','idnumber' => '6','frameworkid' => '1','path' => '/21/6','depthid' => '2','parentid' => '21','sortorder' => '20','visible' => '1','timecreated' => '0','timemodified' => '1267684069','usermodified' => '2',),
array('id' => '7','fullname' => 'Wanganui District Office','shortname' => 'Wanganui DO','description' => '','idnumber' => '7','frameworkid' => '1','path' => '/21/7','depthid' => '2','parentid' => '21','sortorder' => '24','visible' => '1','timecreated' => '0','timemodified' => '1267684182','usermodified' => '2',),
array('id' => '9','fullname' => 'Wellington Hawke\\\'s Bay District Office','shortname' => 'Wellington Hawke\\\'s Bay DO','idnumber' => '9','frameworkid' => '1','path' => '/21/9','depthid' => '2','parentid' => '21','sortorder' => '29','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '10','fullname' => 'Nelson Marlborough District Office','shortname' => 'Nelson Marlborough DO','idnumber' => '10','frameworkid' => '1','path' => '/23/10','depthid' => '2','parentid' => '23','sortorder' => '36','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '11','fullname' => 'West Coast Tai Poutini District Office','shortname' => 'West Coast Tai Poutini DO','idnumber' => '11','frameworkid' => '1','path' => '/23/11','depthid' => '2','parentid' => '23','sortorder' => '42','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '12','fullname' => 'Canterbury District Office','shortname' => 'Canterbury District Office','idnumber' => '12','frameworkid' => '1','path' => '/23/12','depthid' => '2','parentid' => '23','sortorder' => '48','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '13','fullname' => 'Southland District Office','shortname' => 'Southland District Office','idnumber' => '13','frameworkid' => '1','path' => '/23/13','depthid' => '2','parentid' => '23','sortorder' => '54','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '14','fullname' => 'Southland Conservancy Office','shortname' => 'Southland CO','idnumber' => '14','frameworkid' => '1','path' => '/23/14','depthid' => '2','parentid' => '23','sortorder' => '59','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '21','fullname' => 'North Island','shortname' => 'NO','description' => '','idnumber' => '21','frameworkid' => '1','path' => '/21','depthid' => '1','parentid' => '0','sortorder' => '1','visible' => '1','timecreated' => '0','timemodified' => '1267679378','usermodified' => '2',),
array('id' => '23','fullname' => 'South Island','shortname' => 'South Island','description' => '','idnumber' => '23','frameworkid' => '1','path' => '/23','depthid' => '1','parentid' => '0','sortorder' => '35','visible' => '1','timecreated' => '0','timemodified' => '1267679437','usermodified' => '2',),
array('id' => '26','fullname' => 'National Office','shortname' => 'National Office','idnumber' => '26','frameworkid' => '2','path' => '/26','depthid' => '4','parentid' => '0','sortorder' => '100','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '106','fullname' => 'Kauri Coast Area Office','shortname' => 'Kauri Coast AO','idnumber' => '106','frameworkid' => '1','path' => '/21/1/106','depthid' => '3','parentid' => '1','sortorder' => '3','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '111','fullname' => 'Kaitaia Area Office','shortname' => 'Kaitaia AO','idnumber' => '111','frameworkid' => '1','path' => '/21/1/111','depthid' => '3','parentid' => '1','sortorder' => '4','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '112','fullname' => 'Bay of Islands Area Office','shortname' => 'Bay of Islands AO','idnumber' => '112','frameworkid' => '1','path' => '/21/1/112','depthid' => '3','parentid' => '1','sortorder' => '5','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '113','fullname' => 'Whangarei Area Office','shortname' => 'Whangarei AO','idnumber' => '113','frameworkid' => '1','path' => '/21/1/113','depthid' => '3','parentid' => '1','sortorder' => '6','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '211','fullname' => 'Auckland Area Office','shortname' => 'Auckland AO','idnumber' => '211','frameworkid' => '1','path' => '/21/2/211','depthid' => '3','parentid' => '2','sortorder' => '8','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '212','fullname' => 'Great Barrier Area Office','shortname' => 'Great Barrier AO','idnumber' => '212','frameworkid' => '1','path' => '/21/2/212','depthid' => '3','parentid' => '2','sortorder' => '9','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '213','fullname' => 'Warkworth Area Office','shortname' => 'Warkworth AO','idnumber' => '213','frameworkid' => '1','path' => '/21/2/213','depthid' => '3','parentid' => '2','sortorder' => '10','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '311','fullname' => 'Hauraki Area Office','shortname' => 'Hauraki AO','idnumber' => '311','frameworkid' => '1','path' => '/21/3/311','depthid' => '3','parentid' => '3','sortorder' => '12','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '312','fullname' => 'Maniapoto Area Office','shortname' => 'Maniapoto AO','idnumber' => '312','frameworkid' => '1','path' => '/21/3/312','depthid' => '3','parentid' => '3','sortorder' => '13','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '313','fullname' => 'Waikato Area Office','shortname' => 'Waikato AO','idnumber' => '313','frameworkid' => '1','path' => '/21/3/313','depthid' => '3','parentid' => '3','sortorder' => '14','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '411','fullname' => 'Te Urewera Area Office','shortname' => 'Te Urewera AO','idnumber' => '411','frameworkid' => '1','path' => '/21/4/411','depthid' => '3','parentid' => '4','sortorder' => '16','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '412','fullname' => 'Rotorua Lakes Area Office','shortname' => 'Rotorua Lakes AO','idnumber' => '412','frameworkid' => '1','path' => '/21/4/412','depthid' => '3','parentid' => '4','sortorder' => '17','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '413','fullname' => 'Tauranga Area Office','shortname' => 'Tauranga AO','idnumber' => '413','frameworkid' => '1','path' => '/21/4/413','depthid' => '3','parentid' => '4','sortorder' => '18','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '611','fullname' => 'Ruapehu Area Office','shortname' => 'Ruapehu AO','idnumber' => '611','frameworkid' => '1','path' => '/21/6/611','depthid' => '3','parentid' => '6','sortorder' => '21','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '612','fullname' => 'Taupo Fishery Area Office','shortname' => 'Taupo Fishery AO','idnumber' => '612','frameworkid' => '1','path' => '/21/6/612','depthid' => '3','parentid' => '6','sortorder' => '22','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '613','fullname' => 'Turangi/Taupo Area Office','shortname' => 'Turangi/Taupo AO','idnumber' => '613','frameworkid' => '1','path' => '/21/6/613','depthid' => '3','parentid' => '6','sortorder' => '23','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '711','fullname' => 'Taranaki Area Office','shortname' => 'Taranaki AO','idnumber' => '711','frameworkid' => '1','path' => '/21/7/711','depthid' => '3','parentid' => '7','sortorder' => '25','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '712','fullname' => 'Palmerston North Area Office','shortname' => 'Palmerston North AO','idnumber' => '712','frameworkid' => '1','path' => '/21/7/712','depthid' => '3','parentid' => '7','sortorder' => '26','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '713','fullname' => 'Stratford Area Office','shortname' => 'Stratford AO','idnumber' => '713','frameworkid' => '1','path' => '/21/7/713','depthid' => '3','parentid' => '7','sortorder' => '27','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '714','fullname' => 'Whanganui Area Office','shortname' => 'Whanganui AO','idnumber' => '714','frameworkid' => '1','path' => '/21/7/714','depthid' => '3','parentid' => '7','sortorder' => '28','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '812','fullname' => 'Gisborne Whakatane Area Office','shortname' => 'Gisborne Whakatane AO','idnumber' => '812','frameworkid' => '1','path' => '/21/4/812','depthid' => '3','parentid' => '4','sortorder' => '19','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '813','fullname' => 'Hawke\\\'s Bay Area Office','shortname' => 'Hawke\\\'s Bay AO','idnumber' => '813','frameworkid' => '1','path' => '/21/9/813','depthid' => '3','parentid' => '9','sortorder' => '30','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '911','fullname' => 'Chatham Islands Area Office','shortname' => 'Chatham Islands AO','idnumber' => '911','frameworkid' => '1','path' => '/21/9/911','depthid' => '3','parentid' => '9','sortorder' => '31','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '912','fullname' => 'Kapiti Area Office','shortname' => 'Kapiti AO','idnumber' => '912','frameworkid' => '1','path' => '/21/9/912','depthid' => '3','parentid' => '9','sortorder' => '32','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '913','fullname' => 'Wairarapa Area Office','shortname' => 'Wairarapa AO','idnumber' => '913','frameworkid' => '1','path' => '/21/9/913','depthid' => '3','parentid' => '9','sortorder' => '33','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '914','fullname' => 'Poneke Area Office','shortname' => 'Poneke AO','idnumber' => '914','frameworkid' => '1','path' => '/21/9/914','depthid' => '3','parentid' => '9','sortorder' => '34','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1011','fullname' => 'Golden Bay Area Office','shortname' => 'Golden Bay AO','idnumber' => '1011','frameworkid' => '1','path' => '/23/10/1011','depthid' => '3','parentid' => '10','sortorder' => '37','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1012','fullname' => 'Motueka Area Office','shortname' => 'Motueka AO','idnumber' => '1012','frameworkid' => '1','path' => '/23/10/1012','depthid' => '3','parentid' => '10','sortorder' => '38','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1013','fullname' => 'Sounds Area Office','shortname' => 'Sounds AO','idnumber' => '1013','frameworkid' => '1','path' => '/23/10/1013','depthid' => '3','parentid' => '10','sortorder' => '39','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1014','fullname' => 'South Marlborough Area Office','shortname' => 'South Marlborough AO','idnumber' => '1014','frameworkid' => '1','path' => '/23/10/1014','depthid' => '3','parentid' => '10','sortorder' => '40','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1015','fullname' => 'Nelson Lakes Area Office','shortname' => 'Nelson Lakes AO','idnumber' => '1015','frameworkid' => '1','path' => '/23/10/1015','depthid' => '3','parentid' => '10','sortorder' => '41','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1111','fullname' => 'South Westland - Weheka Area Office','shortname' => 'South Westland - Weheka AO','idnumber' => '1111','frameworkid' => '1','path' => '/23/11/1111','depthid' => '3','parentid' => '11','sortorder' => '43','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1112','fullname' => 'Franz Josef - Waiau Area Office','shortname' => 'Franz Josef - Waiau AO','idnumber' => '1112','frameworkid' => '1','path' => '/23/11/1112','depthid' => '3','parentid' => '11','sortorder' => '44','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1113','fullname' => 'Greymouth - Mawheranui Area Office','shortname' => 'Greymouth - Mawheranui AO','idnumber' => '1113','frameworkid' => '1','path' => '/23/11/1113','depthid' => '3','parentid' => '11','sortorder' => '45','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1114','fullname' => 'Hokitika Area Office','shortname' => 'Hokitika AO','idnumber' => '1114','frameworkid' => '1','path' => '/23/11/1114','depthid' => '3','parentid' => '11','sortorder' => '46','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1115','fullname' => 'Buller - Kawatiri Area Office','shortname' => 'Buller - Kawatiri AO','idnumber' => '1115','frameworkid' => '1','path' => '/23/11/1115','depthid' => '3','parentid' => '11','sortorder' => '47','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1211','fullname' => 'Aoraki Area Office','shortname' => 'Aoraki AO','idnumber' => '1211','frameworkid' => '1','path' => '/23/12/1211','depthid' => '3','parentid' => '12','sortorder' => '49','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1212','fullname' => 'Mahaanui Area Office','shortname' => 'Mahaanui AO','idnumber' => '1212','frameworkid' => '1','path' => '/23/12/1212','depthid' => '3','parentid' => '12','sortorder' => '50','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1213','fullname' => 'Raukapuka Area Office','shortname' => 'Raukapuka AO','idnumber' => '1213','frameworkid' => '1','path' => '/23/12/1213','depthid' => '3','parentid' => '12','sortorder' => '51','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1214','fullname' => 'Twizel Area Office','shortname' => 'Twizel AO','idnumber' => '1214','frameworkid' => '1','path' => '/23/12/1214','depthid' => '3','parentid' => '12','sortorder' => '52','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1215','fullname' => 'Waimakariri Area Office','shortname' => 'Waimakariri AO','idnumber' => '1215','frameworkid' => '1','path' => '/23/12/1215','depthid' => '3','parentid' => '12','sortorder' => '53','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1311','fullname' => 'Central Otago Area Office','shortname' => 'Central Otago AO','idnumber' => '1311','frameworkid' => '1','path' => '/23/13/1311','depthid' => '3','parentid' => '13','sortorder' => '55','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1312','fullname' => 'Coastal Otago Area Office','shortname' => 'Coastal Otago AO','idnumber' => '1312','frameworkid' => '1','path' => '/23/13/1312','depthid' => '3','parentid' => '13','sortorder' => '56','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1313','fullname' => 'Wakatipu Area Office','shortname' => 'Wakatipu AO','idnumber' => '1313','frameworkid' => '1','path' => '/23/13/1313','depthid' => '3','parentid' => '13','sortorder' => '57','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1314','fullname' => 'Wanaka Area Office','shortname' => 'Wanaka AO','idnumber' => '1314','frameworkid' => '1','path' => '/23/13/1314','depthid' => '3','parentid' => '13','sortorder' => '58','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1411','fullname' => 'Murihiku Area Office','shortname' => 'Murihiku AO','idnumber' => '1411','frameworkid' => '1','path' => '/23/14/1411','depthid' => '3','parentid' => '14','sortorder' => '60','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1412','fullname' => 'Southern Islands Area Office','shortname' => 'Southern Islands AO','idnumber' => '1412','frameworkid' => '1','path' => '/23/14/1412','depthid' => '3','parentid' => '14','sortorder' => '61','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '1413','fullname' => 'Te Anau Area Office','shortname' => 'Te Anau AO','idnumber' => '1413','frameworkid' => '1','path' => '/23/14/1413','depthid' => '3','parentid' => '14','sortorder' => '62','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2000','fullname' => 'Human Resources Group','shortname' => 'Human Resources Group','description' => '','idnumber' => '2000','frameworkid' => '2','path' => '/26/2000','depthid' => '5','parentid' => '26','sortorder' => '101','visible' => '1','timecreated' => '0','timemodified' => '1267684534','usermodified' => '2',),
array('id' => '2001','fullname' => 'Corporate Services Group','shortname' => 'Corporate Services BG','idnumber' => '2001','frameworkid' => '2','path' => '/26/2001','depthid' => '5','parentid' => '26','sortorder' => '106','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2002','fullname' => 'Marketing and Communications Group','shortname' => 'Marketing and Communications BG','idnumber' => '2002','frameworkid' => '2','path' => '/26/2002','depthid' => '5','parentid' => '26','sortorder' => '111','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2003','fullname' => 'Research and Development Group','shortname' => 'Research and Development BG','idnumber' => '2003','frameworkid' => '2','path' => '/26/2003','depthid' => '5','parentid' => '26','sortorder' => '117','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2004','fullname' => 'Policy Group','shortname' => 'Policy BG','idnumber' => '2004','frameworkid' => '2','path' => '/26/2004','depthid' => '5','parentid' => '26','sortorder' => '122','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2005','fullname' => 'Mergers and Acquisitions Group','shortname' => 'Mergers and Acquisitions BG','description' => '','idnumber' => '2005','frameworkid' => '2','path' => '/26/2005','depthid' => '5','parentid' => '26','sortorder' => '125','visible' => '1','timecreated' => '0','timemodified' => '1267684726','usermodified' => '2',),
array('id' => '2006','fullname' => 'Employee Relations Unit','shortname' => 'Employee Relations BU','idnumber' => '2006','frameworkid' => '2','path' => '/26/2000/2006','depthid' => '6','parentid' => '2000','sortorder' => '102','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2007','fullname' => 'Organisation Development Unit','shortname' => 'Organisation Development BU','idnumber' => '2007','frameworkid' => '2','path' => '/26/2000/2007','depthid' => '6','parentid' => '2000','sortorder' => '103','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2008','fullname' => 'Internal Audit Unit','shortname' => 'Internal Audit BU','idnumber' => '2008','frameworkid' => '2','path' => '/26/2000/2008','depthid' => '6','parentid' => '2000','sortorder' => '104','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2009','fullname' => 'Strategy Team','shortname' => 'Strategy T','idnumber' => '2009','frameworkid' => '2','path' => '/26/2000/2009','depthid' => '6','parentid' => '2000','sortorder' => '105','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2010','fullname' => 'Strategic Finance Unit','shortname' => 'Strategic Finance BU','idnumber' => '2010','frameworkid' => '2','path' => '/26/2001/2010','depthid' => '6','parentid' => '2001','sortorder' => '107','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2011','fullname' => 'Financial Operations Unit','shortname' => 'Financial Operations BU','idnumber' => '2011','frameworkid' => '2','path' => '/26/2001/2011','depthid' => '6','parentid' => '2001','sortorder' => '108','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2012','fullname' => 'Information Services Unit','shortname' => 'Information Services BU','idnumber' => '2012','frameworkid' => '2','path' => '/26/2001/2012','depthid' => '6','parentid' => '2001','sortorder' => '109','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2013','fullname' => 'Legal Services Unit','shortname' => 'Legal Services BU','idnumber' => '2013','frameworkid' => '2','path' => '/26/2001/2013','depthid' => '6','parentid' => '2001','sortorder' => '110','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2014','fullname' => 'Communications Unit','shortname' => 'Communications BU','idnumber' => '2014','frameworkid' => '2','path' => '/26/2002/2014','depthid' => '6','parentid' => '2002','sortorder' => '112','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2015','fullname' => 'International Relations Unit','shortname' => 'International Relations BU','idnumber' => '2015','frameworkid' => '2','path' => '/26/2002/2015','depthid' => '6','parentid' => '2002','sortorder' => '113','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2016','fullname' => 'Marketing Unit','shortname' => 'Marketing BU','idnumber' => '2016','frameworkid' => '2','path' => '/26/2002/2016','depthid' => '6','parentid' => '2002','sortorder' => '114','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2017','fullname' => 'Brand Management Unit','shortname' => 'Brand Management BU','description' => '','idnumber' => '2017','frameworkid' => '2','path' => '/26/2002/2017','depthid' => '6','parentid' => '2002','sortorder' => '115','visible' => '1','timecreated' => '0','timemodified' => '1267684861','usermodified' => '2',),
array('id' => '2018','fullname' => 'Relationships Unit','shortname' => 'Relationships BU','idnumber' => '2018','frameworkid' => '2','path' => '/26/2002/2018','depthid' => '6','parentid' => '2002','sortorder' => '116','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2019','fullname' => 'Technical Services Unit','shortname' => 'Ecosystems and Species BU','description' => '','idnumber' => '2019','frameworkid' => '2','path' => '/26/2003/2019','depthid' => '6','parentid' => '2003','sortorder' => '118','visible' => '1','timecreated' => '0','timemodified' => '1267684784','usermodified' => '2',),
array('id' => '2020','fullname' => 'Policy Research Unit','shortname' => 'Policy Research BU','description' => '','idnumber' => '2020','frameworkid' => '2','path' => '/26/2003/2020','depthid' => '6','parentid' => '2003','sortorder' => '119','visible' => '1','timecreated' => '0','timemodified' => '1267684822','usermodified' => '2',),
array('id' => '2021','fullname' => 'Licensing Research Unit','shortname' => 'Licensing Research BU','description' => '','idnumber' => '2021','frameworkid' => '2','path' => '/26/2003/2021','depthid' => '6','parentid' => '2003','sortorder' => '120','visible' => '1','timecreated' => '0','timemodified' => '1267684932','usermodified' => '2',),
array('id' => '2022','fullname' => 'National Technical Services Unit','shortname' => 'National Technical Services BU','idnumber' => '2022','frameworkid' => '2','path' => '/26/2003/2022','depthid' => '6','parentid' => '2003','sortorder' => '121','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2023','fullname' => 'Planning Unit','shortname' => 'Planning BU','idnumber' => '2023','frameworkid' => '2','path' => '/26/2004/2023','depthid' => '6','parentid' => '2004','sortorder' => '123','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2024','fullname' => 'Policy Negotiations Unit','shortname' => 'Policy Negotiations BU','idnumber' => '2024','frameworkid' => '2','path' => '/26/2004/2024','depthid' => '6','parentid' => '2004','sortorder' => '124','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '2025','fullname' => 'Mergers and Acquisitions Unit','shortname' => 'Mergers and Acquisitions BU','description' => '','idnumber' => '2025','frameworkid' => '2','path' => '/26/2005/2025','depthid' => '6','parentid' => '2005','sortorder' => '126','visible' => '1','timecreated' => '0','timemodified' => '1267684752','usermodified' => '2',),
array('id' => '3000','fullname' => 'Empowerment Training Limited (External)','shortname' => 'Empowerment Training Limited (EXT)','description' => '','idnumber' => '3000','frameworkid' => '3','path' => '/3000','depthid' => '7','parentid' => '0','sortorder' => '1','visible' => '1','timecreated' => '0','timemodified' => '1267685637','usermodified' => '2',),
array('id' => '3001','fullname' => 'Online Training Center (External)','shortname' => 'Online Training Center (EXT)','description' => '','idnumber' => '3001','frameworkid' => '3','path' => '/3001','depthid' => '7','parentid' => '0','sortorder' => '2','visible' => '1','timecreated' => '0','timemodified' => '1267685663','usermodified' => '2',),
array('id' => '3002','fullname' => 'Competency Development Corporation (External)','shortname' => 'Competency Development Corporation (EXT)','description' => '','idnumber' => '3002','frameworkid' => '3','path' => '/3002','depthid' => '7','parentid' => '0','sortorder' => '3','visible' => '1','timecreated' => '0','timemodified' => '1267685901','usermodified' => '2',),
array('id' => '3003','fullname' => 'Development Dynamics Limited (External)','shortname' => 'Development Dynamics Limited (EXT)','description' => '','idnumber' => '3003','frameworkid' => '3','path' => '/3003','depthid' => '7','parentid' => '0','sortorder' => '4','visible' => '1','timecreated' => '0','timemodified' => '1267685934','usermodified' => '2',),
array('id' => '3004','fullname' => 'Leading Media Associates (External)','shortname' => 'Leading Media Associates (EXT)','description' => '','idnumber' => '3004','frameworkid' => '3','path' => '/3004','depthid' => '7','parentid' => '0','sortorder' => '5','visible' => '1','timecreated' => '0','timemodified' => '1267685871','usermodified' => '2',),
array('id' => '3005','fullname' => 'Davis Professionall Services (External)','shortname' => 'Davis Professional Services (EXT)','description' => '','idnumber' => '3005','frameworkid' => '3','path' => '/3005','depthid' => '7','parentid' => '0','sortorder' => '6','visible' => '1','timecreated' => '0','timemodified' => '1267686042','usermodified' => '2',),
array('id' => '3006','fullname' => 'Corporate University (External)','shortname' => 'Corporate University (EXT)','description' => '','idnumber' => '3006','frameworkid' => '3','path' => '/3006','depthid' => '7','parentid' => '0','sortorder' => '7','visible' => '1','timecreated' => '0','timemodified' => '1267686069','usermodified' => '2',),
array('id' => '3007','fullname' => 'Proquest Services (External)','shortname' => 'Proquest Services (EXT)','description' => '','idnumber' => '3007','frameworkid' => '3','path' => '/3007','depthid' => '7','parentid' => '0','sortorder' => '8','visible' => '1','timecreated' => '0','timemodified' => '1267686106','usermodified' => '2',),
array('id' => '3008','fullname' => 'Enterprise Experts (External)','shortname' => 'Enterprise Experts (EXT)','description' => '','idnumber' => '3008','frameworkid' => '3','path' => '/3008','depthid' => '7','parentid' => '0','sortorder' => '9','visible' => '1','timecreated' => '0','timemodified' => '1267686180','usermodified' => '2',),
array('id' => '3009','fullname' => 'Workplace Environment Support Centre (External)','shortname' => 'Workplace Environment Support Centre (EXT)','description' => '','idnumber' => '3009','frameworkid' => '3','path' => '/3009','depthid' => '7','parentid' => '0','sortorder' => '10','visible' => '1','timecreated' => '0','timemodified' => '1267686142','usermodified' => '2',),
array('id' => '3010','fullname' => 'Creative Coaching Inc. (External)','shortname' => 'Creative Coaching Inc. (EXT)','description' => '','idnumber' => '3010','frameworkid' => '3','path' => '/3010','depthid' => '7','parentid' => '0','sortorder' => '11','visible' => '1','timecreated' => '0','timemodified' => '1267686011','usermodified' => '2',),
array('id' => '3011','fullname' => 'Rich & Davis Ltd (External)','shortname' => 'Rich & Davis Ltd (EXT)','description' => '','idnumber' => '3011','frameworkid' => '3','path' => '/3011','depthid' => '7','parentid' => '0','sortorder' => '12','visible' => '1','timecreated' => '0','timemodified' => '1267685979','usermodified' => '2',),
array('id' => '3012','fullname' => 'FrameWork Group Ltd (External)','shortname' => 'FrameWork Group Ltd (EXT)','description' => '','idnumber' => '3012','frameworkid' => '3','path' => '/3012','depthid' => '7','parentid' => '0','sortorder' => '13','visible' => '1','timecreated' => '0','timemodified' => '1267685848','usermodified' => '2',),
array('id' => '3013','fullname' => 'Capital Training House (External)','shortname' => 'Capital Training House (EXT)','description' => '','idnumber' => '3013','frameworkid' => '3','path' => '/3013','depthid' => '7','parentid' => '0','sortorder' => '14','visible' => '1','timecreated' => '0','timemodified' => '1267685821','usermodified' => '2',),
array('id' => '3014','fullname' => 'Pioneer Business Centre (External)','shortname' => 'Pioneer Business Centre (EXT)','description' => '','idnumber' => '3014','frameworkid' => '3','path' => '/3014','depthid' => '7','parentid' => '0','sortorder' => '15','visible' => '1','timecreated' => '0','timemodified' => '1267685786','usermodified' => '2',),
array('id' => '3015','fullname' => 'Enterprise Central Network Inc. (External)','shortname' => 'Enterprise Central Network Inc. (EXT)','description' => '','idnumber' => '3015','frameworkid' => '3','path' => '/3015','depthid' => '7','parentid' => '0','sortorder' => '16','visible' => '1','timecreated' => '0','timemodified' => '1267685405','usermodified' => '2',),
array('id' => '3016','fullname' => 'Venture Services (External)','shortname' => 'Venture Services (EXT)','description' => '','idnumber' => '3016','frameworkid' => '3','path' => '/3016','depthid' => '7','parentid' => '0','sortorder' => '17','visible' => '1','timecreated' => '0','timemodified' => '1267685702','usermodified' => '2',),
array('id' => '3017','fullname' => 'Business Training Services (External)','shortname' => 'Business Training Services (EXT)','description' => '','idnumber' => '3017','frameworkid' => '3','path' => '/3017','depthid' => '7','parentid' => '0','sortorder' => '18','visible' => '1','timecreated' => '0','timemodified' => '1267685754','usermodified' => '2',),
array('id' => '3018','fullname' => 'Enterprise Central (External)','shortname' => 'Enterprise Central (EXT)','description' => '','idnumber' => '3018','frameworkid' => '3','path' => '/3018','depthid' => '7','parentid' => '0','sortorder' => '19','visible' => '1','timecreated' => '0','timemodified' => '1267685727','usermodified' => '2',),
array('id' => '3019','fullname' => 'Workforce Training Limited (External)','shortname' => 'Workforce Training Limited','description' => '','idnumber' => '3019','frameworkid' => '3','path' => '/3019','depthid' => '7','parentid' => '0','sortorder' => '20','visible' => '1','timecreated' => '0','timemodified' => '1267685607','usermodified' => '2',),
array('id' => '3020','fullname' => 'Kiwi Recovery Group (External)','shortname' => 'Kiwi Recovery Group (EXT)','idnumber' => '3020','frameworkid' => '3','path' => '/3020','depthid' => '7','parentid' => '0','sortorder' => '21','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3021','fullname' => 'Landcare Research Ltd (External)','shortname' => 'Landcare Research Ltd (EXT)','idnumber' => '3021','frameworkid' => '3','path' => '/3021','depthid' => '7','parentid' => '0','sortorder' => '22','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3022','fullname' => 'Lincoln University (External)','shortname' => 'Lincoln University (EXT)','idnumber' => '3022','frameworkid' => '3','path' => '/3022','depthid' => '7','parentid' => '0','sortorder' => '23','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3023','fullname' => 'Manawhe Corridor Care Group (External)','shortname' => 'Manawhe Corridor Care Group (EXT)','idnumber' => '3023','frameworkid' => '3','path' => '/3023','depthid' => '7','parentid' => '0','sortorder' => '24','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3024','fullname' => 'Massey University (External)','shortname' => 'Massey University (EXT)','idnumber' => '3024','frameworkid' => '3','path' => '/3024','depthid' => '7','parentid' => '0','sortorder' => '25','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3025','fullname' => 'Motuihe Trust (External)','shortname' => 'Motuihe Trust (EXT)','idnumber' => '3025','frameworkid' => '3','path' => '/3025','depthid' => '7','parentid' => '0','sortorder' => '26','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3026','fullname' => 'Motutapu Restoration Trust (External)','shortname' => 'Motutapu Restoration Trust (EXT)','idnumber' => '3026','frameworkid' => '3','path' => '/3026','depthid' => '7','parentid' => '0','sortorder' => '27','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3027','fullname' => 'Nelson Boys College Teacher (External)','shortname' => 'Nelson Boys College Teacher (EXT)','idnumber' => '3027','frameworkid' => '3','path' => '/3027','depthid' => '7','parentid' => '0','sortorder' => '28','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3028','fullname' => 'Nelson Environment Centre (External)','shortname' => 'Nelson Environment Centre (EXT)','idnumber' => '3028','frameworkid' => '3','path' => '/3028','depthid' => '7','parentid' => '0','sortorder' => '29','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3029','fullname' => 'Nga Puhi (External)','shortname' => 'Nga Puhi (EXT)','idnumber' => '3029','frameworkid' => '3','path' => '/3029','depthid' => '7','parentid' => '0','sortorder' => '30','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3030','fullname' => 'Ngati Rehua Trust Board Member (External)','shortname' => 'Ngati Rehua Trust Board Member (EXT)','idnumber' => '3030','frameworkid' => '3','path' => '/3030','depthid' => '7','parentid' => '0','sortorder' => '31','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3031','fullname' => 'NMIT (External)','shortname' => 'NMIT (EXT)','idnumber' => '3031','frameworkid' => '3','path' => '/3031','depthid' => '7','parentid' => '0','sortorder' => '32','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3032','fullname' => 'Ohiwa Care Group (External)','shortname' => 'Ohiwa Care Group (EXT)','idnumber' => '3032','frameworkid' => '3','path' => '/3032','depthid' => '7','parentid' => '0','sortorder' => '33','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3033','fullname' => 'Pomona Island Charitable Trust (External)','shortname' => 'Pomona Island Charitable Trust (EXT)','idnumber' => '3033','frameworkid' => '3','path' => '/3033','depthid' => '7','parentid' => '0','sortorder' => '34','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3034','fullname' => 'QEII National Trust (External)','shortname' => 'QEII National Trust (EXT)','idnumber' => '3034','frameworkid' => '3','path' => '/3034','depthid' => '7','parentid' => '0','sortorder' => '35','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3035','fullname' => 'Rangitoto island Historic Conservation Trust   (External)','shortname' => 'Rangitoto island Historic Conservation Trust   (EXT)','idnumber' => '3035','frameworkid' => '3','path' => '/3035','depthid' => '7','parentid' => '0','sortorder' => '36','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3036','fullname' => 'Riverside Community (External)','shortname' => 'Riverside Community (EXT)','idnumber' => '3036','frameworkid' => '3','path' => '/3036','depthid' => '7','parentid' => '0','sortorder' => '37','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3037','fullname' => 'Royal Forest and Bird Protection Society of NZ Inc (External)','shortname' => 'Royal Forest and Bird Protection Society of NZ Inc (EXT)','idnumber' => '3037','frameworkid' => '3','path' => '/3037','depthid' => '7','parentid' => '0','sortorder' => '38','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3038','fullname' => 'South Otago Museum (External)','shortname' => 'South Otago Museum (EXT)','idnumber' => '3038','frameworkid' => '3','path' => '/3038','depthid' => '7','parentid' => '0','sortorder' => '39','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3039','fullname' => 'Stewart Island Rakiura Community Trust (External)','shortname' => 'Stewart Island Rakiura Community Trust (EXT)','idnumber' => '3039','frameworkid' => '3','path' => '/3039','depthid' => '7','parentid' => '0','sortorder' => '40','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3040','fullname' => 'Taranaki Regional Council (External)','shortname' => 'Taranaki Regional Council (EXT)','idnumber' => '3040','frameworkid' => '3','path' => '/3040','depthid' => '7','parentid' => '0','sortorder' => '41','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3041','fullname' => 'The Kauri Museum (External)','shortname' => 'The Kauri Museum (EXT)','idnumber' => '3041','frameworkid' => '3','path' => '/3041','depthid' => '7','parentid' => '0','sortorder' => '42','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3042','fullname' => 'The Terrace School (External)','shortname' => 'The Terrace School (EXT)','idnumber' => '3042','frameworkid' => '3','path' => '/3042','depthid' => '7','parentid' => '0','sortorder' => '43','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3043','fullname' => 'Tongariro Natural History Soc  (External)','shortname' => 'Tongariro Natural History Soc  (EXT)','idnumber' => '3043','frameworkid' => '3','path' => '/3043','depthid' => '7','parentid' => '0','sortorder' => '44','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3044','fullname' => 'UNITEC (External)','shortname' => 'UNITEC (EXT)','idnumber' => '3044','frameworkid' => '3','path' => '/3044','depthid' => '7','parentid' => '0','sortorder' => '45','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3045','fullname' => 'University of Auckland (External)','shortname' => 'University of Auckland (EXT)','idnumber' => '3045','frameworkid' => '3','path' => '/3045','depthid' => '7','parentid' => '0','sortorder' => '46','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3046','fullname' => 'University of Canterbury (External)','shortname' => 'University of Canterbury (EXT)','idnumber' => '3046','frameworkid' => '3','path' => '/3046','depthid' => '7','parentid' => '0','sortorder' => '47','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
array('id' => '3047','fullname' => 'University of Otago (External)','shortname' => 'University of Otago (EXT)','idnumber' => '3047','frameworkid' => '3','path' => '/3047','depthid' => '7','parentid' => '0','sortorder' => '48','visible' => '1','timecreated' => '0','timemodified' => '0','usermodified' => '2',),
);
print "\n";print "Inserting ".count($items)." records<br />\n";
$i=1;
foreach($items as $item) {
    if(get_field('org', 'id', 'id', $item['id'])) {
        print "Record with id of {$item['id']} already exists!<br>\n";
        continue;
    }
    $newid = insert_record('org',(object) $item);
    if($newid != $item['id']) {
        if(!set_field('org', 'id', $item['id'], 'id', $newid)) {
            print "Could not change id from $newid to {$item['id']}<br>\n";
            continue;
        }
    }
    // record the highest id in the table
    $maxid = get_field_sql('SELECT '.sql_max('id').' FROM '.$CFG->prefix.'org');
    // make sure sequence is higher than highest ID
    bump_sequence('org', $CFG->prefix, $maxid);
    // print output
    // 1 dot per 10 inserts
    if($i%10==0) {
        print ".";
        flush();
    }
    // new line every 200 dots
    if($i%2000==0) {
        print $i." <br>";
    }
    $i++;
}
print "<br>";

set_config("guestloginbutton", 0);
set_config("langmenu", 0);
set_config("forcelogin", 1);
        