<?php
@raise_memory_limit('496M');
@ini_set('max_execution_time','3000');
print "Loading data for table 'feedback'<br>";
$items = array(array('id' => '2','course' => '45','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '3','course' => '61','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '4','course' => '22','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '5','course' => '217','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '6','course' => '108','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '7','course' => '33','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '8','course' => '68','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '9','course' => '70','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '10','course' => '3','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '11','course' => '4','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '12','course' => '5','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '13','course' => '7','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '14','course' => '8','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '15','course' => '9','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '16','course' => '10','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '17','course' => '12','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '18','course' => '13','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '19','course' => '14','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '20','course' => '15','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '21','course' => '16','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '22','course' => '17','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '23','course' => '19','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '24','course' => '20','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '25','course' => '21','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '26','course' => '23','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '27','course' => '24','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '28','course' => '25','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '29','course' => '26','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '30','course' => '27','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '31','course' => '28','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '32','course' => '30','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '33','course' => '32','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '34','course' => '34','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '35','course' => '36','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '36','course' => '38','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '37','course' => '39','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '38','course' => '40','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '39','course' => '41','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '40','course' => '42','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '41','course' => '43','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '42','course' => '44','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '43','course' => '46','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '44','course' => '47','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '45','course' => '48','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '46','course' => '49','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '47','course' => '50','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '48','course' => '51','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '49','course' => '52','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '50','course' => '53','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '51','course' => '55','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '52','course' => '58','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '53','course' => '59','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '54','course' => '60','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '55','course' => '62','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '56','course' => '64','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '57','course' => '65','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '58','course' => '66','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '59','course' => '69','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '60','course' => '71','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '61','course' => '72','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '62','course' => '73','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '63','course' => '74','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '64','course' => '75','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '65','course' => '76','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '66','course' => '77','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '67','course' => '78','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '68','course' => '79','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '69','course' => '80','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '70','course' => '81','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '71','course' => '82','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '72','course' => '83','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '73','course' => '84','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '74','course' => '85','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '75','course' => '86','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '76','course' => '87','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '77','course' => '89','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '78','course' => '90','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '79','course' => '91','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '80','course' => '92','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '81','course' => '93','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '82','course' => '95','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '83','course' => '96','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '84','course' => '97','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '85','course' => '98','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '86','course' => '99','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '87','course' => '100','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '88','course' => '101','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '89','course' => '102','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '90','course' => '103','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '91','course' => '104','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '92','course' => '105','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '93','course' => '106','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '94','course' => '107','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
array('id' => '95','course' => '109','name' => 'Course Evaluation','summary' => '<p>Course evaluation feedback</p>','anonymous' => '1','email_notification' => '0','multiple_submit' => '0','page_after_submit' => '','publish_stats' => '0','timeopen' => '0','timeclose' => '0','timemodified' => '1282789612',),
);
print "\n";print "Inserting ".count($items)." records<br />\n";
$i=1;
foreach($items as $item) {
    if(get_field('feedback', 'id', 'id', $item['id'])) {
        print "Record with id of {$item['id']} already exists!<br>\n";
        continue;
    }
    $newid = insert_record('feedback',(object) $item);
    if($newid != $item['id']) {
        if(!set_field('feedback', 'id', $item['id'], 'id', $newid)) {
            print "Could not change id from $newid to {$item['id']}<br>\n";
            continue;
        }
    }
    // record the highest id in the table
    $maxid = get_field_sql('SELECT '.sql_max('id').' FROM '.$CFG->prefix.'feedback');
    // make sure sequence is higher than highest ID
    bump_sequence('feedback', $CFG->prefix, $maxid);
    // print output
    // 1 dot per 10 inserts
    if($i%10==0) {
        print ".";
        flush();
    }
    // new line every 200 dots
    if($i%2000==0) {
        print $i." <br>";
    }
    $i++;
}
print "<br>";

set_config("guestloginbutton", 0);
set_config("langmenu", 0);
set_config("forcelogin", 1);
        