<?php
@raise_memory_limit('392M');
@ini_set('max_execution_time','3000');
print "Emptytable flag set, deleting all data from block_instance.<br>";
delete_records('block_instance');
print "Loading data for table 'block_instance'<br>";
$items = array(array('id' => '18','blockid' => '28','pageid' => '2','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '19','blockid' => '9','pageid' => '2','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '20','blockid' => '2','pageid' => '2','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '21','blockid' => '7','pageid' => '2','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '22','blockid' => '1','pageid' => '2','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '31','blockid' => '28','pageid' => '3','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '32','blockid' => '9','pageid' => '3','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '33','blockid' => '2','pageid' => '3','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '34','blockid' => '7','pageid' => '3','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '35','blockid' => '1','pageid' => '3','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '44','blockid' => '28','pageid' => '4','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '45','blockid' => '9','pageid' => '4','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '46','blockid' => '2','pageid' => '4','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '47','blockid' => '7','pageid' => '4','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '48','blockid' => '1','pageid' => '4','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '57','blockid' => '28','pageid' => '5','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '58','blockid' => '9','pageid' => '5','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '59','blockid' => '2','pageid' => '5','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '60','blockid' => '7','pageid' => '5','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '61','blockid' => '1','pageid' => '5','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '70','blockid' => '28','pageid' => '6','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '71','blockid' => '9','pageid' => '6','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '72','blockid' => '2','pageid' => '6','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '73','blockid' => '7','pageid' => '6','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '74','blockid' => '1','pageid' => '6','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '83','blockid' => '28','pageid' => '7','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '84','blockid' => '9','pageid' => '7','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '85','blockid' => '2','pageid' => '7','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '86','blockid' => '7','pageid' => '7','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '87','blockid' => '1','pageid' => '7','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '96','blockid' => '28','pageid' => '8','pagetype' => 'course-view','position' => 'r','weight' => '3','visible' => '1','configdata' => 'Tjs=',),
array('id' => '97','blockid' => '9','pageid' => '8','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '98','blockid' => '2','pageid' => '8','pagetype' => 'course-view','position' => 'r','weight' => '4','visible' => '1','configdata' => 'Tjs=',),
array('id' => '99','blockid' => '7','pageid' => '8','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '100','blockid' => '1','pageid' => '8','pagetype' => 'course-view','position' => 'r','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '109','blockid' => '28','pageid' => '9','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '110','blockid' => '9','pageid' => '9','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '111','blockid' => '2','pageid' => '9','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '112','blockid' => '7','pageid' => '9','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '113','blockid' => '1','pageid' => '9','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '122','blockid' => '28','pageid' => '10','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '123','blockid' => '9','pageid' => '10','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '124','blockid' => '2','pageid' => '10','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '125','blockid' => '7','pageid' => '10','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '126','blockid' => '1','pageid' => '10','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '135','blockid' => '28','pageid' => '11','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '136','blockid' => '9','pageid' => '11','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '137','blockid' => '2','pageid' => '11','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '138','blockid' => '7','pageid' => '11','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '139','blockid' => '1','pageid' => '11','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '148','blockid' => '28','pageid' => '12','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '149','blockid' => '9','pageid' => '12','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '150','blockid' => '2','pageid' => '12','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '151','blockid' => '7','pageid' => '12','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '152','blockid' => '1','pageid' => '12','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '161','blockid' => '28','pageid' => '13','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '162','blockid' => '9','pageid' => '13','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '163','blockid' => '2','pageid' => '13','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '164','blockid' => '7','pageid' => '13','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '165','blockid' => '1','pageid' => '13','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '174','blockid' => '28','pageid' => '14','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '175','blockid' => '9','pageid' => '14','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '176','blockid' => '2','pageid' => '14','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '177','blockid' => '7','pageid' => '14','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '178','blockid' => '1','pageid' => '14','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '187','blockid' => '28','pageid' => '15','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '188','blockid' => '9','pageid' => '15','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '189','blockid' => '2','pageid' => '15','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '190','blockid' => '7','pageid' => '15','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '191','blockid' => '1','pageid' => '15','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '200','blockid' => '28','pageid' => '16','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '201','blockid' => '9','pageid' => '16','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '202','blockid' => '2','pageid' => '16','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '203','blockid' => '7','pageid' => '16','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '204','blockid' => '1','pageid' => '16','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '213','blockid' => '28','pageid' => '17','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '214','blockid' => '9','pageid' => '17','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '215','blockid' => '2','pageid' => '17','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '216','blockid' => '7','pageid' => '17','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '217','blockid' => '1','pageid' => '17','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '239','blockid' => '28','pageid' => '19','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '240','blockid' => '9','pageid' => '19','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '241','blockid' => '2','pageid' => '19','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '242','blockid' => '7','pageid' => '19','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '243','blockid' => '1','pageid' => '19','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '252','blockid' => '28','pageid' => '20','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '253','blockid' => '9','pageid' => '20','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '254','blockid' => '2','pageid' => '20','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '255','blockid' => '7','pageid' => '20','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '256','blockid' => '1','pageid' => '20','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '265','blockid' => '28','pageid' => '21','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '266','blockid' => '9','pageid' => '21','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '267','blockid' => '2','pageid' => '21','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '268','blockid' => '7','pageid' => '21','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '269','blockid' => '1','pageid' => '21','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '278','blockid' => '28','pageid' => '22','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '279','blockid' => '9','pageid' => '22','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '280','blockid' => '2','pageid' => '22','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '281','blockid' => '7','pageid' => '22','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '282','blockid' => '1','pageid' => '22','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '291','blockid' => '28','pageid' => '23','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '292','blockid' => '9','pageid' => '23','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '293','blockid' => '2','pageid' => '23','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '294','blockid' => '7','pageid' => '23','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '295','blockid' => '1','pageid' => '23','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '304','blockid' => '28','pageid' => '24','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '305','blockid' => '9','pageid' => '24','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '306','blockid' => '2','pageid' => '24','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '307','blockid' => '7','pageid' => '24','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '308','blockid' => '1','pageid' => '24','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '317','blockid' => '28','pageid' => '25','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '318','blockid' => '9','pageid' => '25','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '319','blockid' => '2','pageid' => '25','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '320','blockid' => '7','pageid' => '25','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '321','blockid' => '1','pageid' => '25','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '330','blockid' => '28','pageid' => '26','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '331','blockid' => '9','pageid' => '26','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '332','blockid' => '2','pageid' => '26','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '333','blockid' => '7','pageid' => '26','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '334','blockid' => '1','pageid' => '26','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '343','blockid' => '28','pageid' => '27','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '344','blockid' => '9','pageid' => '27','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '345','blockid' => '2','pageid' => '27','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '346','blockid' => '7','pageid' => '27','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '347','blockid' => '1','pageid' => '27','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '356','blockid' => '28','pageid' => '28','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '357','blockid' => '9','pageid' => '28','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '358','blockid' => '2','pageid' => '28','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '359','blockid' => '7','pageid' => '28','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '360','blockid' => '1','pageid' => '28','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '369','blockid' => '28','pageid' => '29','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '370','blockid' => '9','pageid' => '29','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '371','blockid' => '2','pageid' => '29','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '372','blockid' => '7','pageid' => '29','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '373','blockid' => '1','pageid' => '29','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '382','blockid' => '28','pageid' => '30','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '383','blockid' => '9','pageid' => '30','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '384','blockid' => '2','pageid' => '30','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '385','blockid' => '7','pageid' => '30','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '386','blockid' => '1','pageid' => '30','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '395','blockid' => '28','pageid' => '31','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '396','blockid' => '9','pageid' => '31','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '397','blockid' => '2','pageid' => '31','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '398','blockid' => '7','pageid' => '31','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '399','blockid' => '1','pageid' => '31','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '408','blockid' => '28','pageid' => '32','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '409','blockid' => '9','pageid' => '32','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '410','blockid' => '2','pageid' => '32','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '411','blockid' => '7','pageid' => '32','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '412','blockid' => '1','pageid' => '32','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '421','blockid' => '28','pageid' => '33','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '422','blockid' => '9','pageid' => '33','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '423','blockid' => '2','pageid' => '33','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '424','blockid' => '7','pageid' => '33','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '425','blockid' => '1','pageid' => '33','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '434','blockid' => '28','pageid' => '34','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '435','blockid' => '9','pageid' => '34','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '436','blockid' => '2','pageid' => '34','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '437','blockid' => '7','pageid' => '34','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '438','blockid' => '1','pageid' => '34','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '447','blockid' => '28','pageid' => '35','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '448','blockid' => '9','pageid' => '35','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '449','blockid' => '2','pageid' => '35','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '450','blockid' => '7','pageid' => '35','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '451','blockid' => '1','pageid' => '35','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '460','blockid' => '28','pageid' => '36','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '461','blockid' => '9','pageid' => '36','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '462','blockid' => '2','pageid' => '36','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '463','blockid' => '7','pageid' => '36','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '464','blockid' => '1','pageid' => '36','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '473','blockid' => '28','pageid' => '37','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '474','blockid' => '9','pageid' => '37','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '475','blockid' => '2','pageid' => '37','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '476','blockid' => '7','pageid' => '37','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '477','blockid' => '1','pageid' => '37','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '486','blockid' => '28','pageid' => '38','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '487','blockid' => '9','pageid' => '38','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '488','blockid' => '2','pageid' => '38','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '489','blockid' => '7','pageid' => '38','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '490','blockid' => '1','pageid' => '38','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '499','blockid' => '28','pageid' => '39','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '500','blockid' => '9','pageid' => '39','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '501','blockid' => '2','pageid' => '39','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '502','blockid' => '7','pageid' => '39','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '503','blockid' => '1','pageid' => '39','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '512','blockid' => '28','pageid' => '40','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '513','blockid' => '9','pageid' => '40','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '514','blockid' => '2','pageid' => '40','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '515','blockid' => '7','pageid' => '40','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '516','blockid' => '1','pageid' => '40','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '525','blockid' => '28','pageid' => '41','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '526','blockid' => '9','pageid' => '41','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '527','blockid' => '2','pageid' => '41','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '528','blockid' => '7','pageid' => '41','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '529','blockid' => '1','pageid' => '41','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '538','blockid' => '28','pageid' => '42','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '539','blockid' => '9','pageid' => '42','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '540','blockid' => '2','pageid' => '42','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '541','blockid' => '7','pageid' => '42','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '542','blockid' => '1','pageid' => '42','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '551','blockid' => '28','pageid' => '43','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '552','blockid' => '9','pageid' => '43','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '553','blockid' => '2','pageid' => '43','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '554','blockid' => '7','pageid' => '43','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '555','blockid' => '1','pageid' => '43','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '564','blockid' => '28','pageid' => '44','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '565','blockid' => '9','pageid' => '44','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '566','blockid' => '2','pageid' => '44','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '567','blockid' => '7','pageid' => '44','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '568','blockid' => '1','pageid' => '44','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '577','blockid' => '28','pageid' => '45','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '578','blockid' => '9','pageid' => '45','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '579','blockid' => '2','pageid' => '45','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '580','blockid' => '7','pageid' => '45','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '581','blockid' => '1','pageid' => '45','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '590','blockid' => '28','pageid' => '46','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '591','blockid' => '9','pageid' => '46','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '592','blockid' => '2','pageid' => '46','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '593','blockid' => '7','pageid' => '46','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '594','blockid' => '1','pageid' => '46','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '603','blockid' => '28','pageid' => '47','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '604','blockid' => '9','pageid' => '47','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '605','blockid' => '2','pageid' => '47','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '606','blockid' => '7','pageid' => '47','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '607','blockid' => '1','pageid' => '47','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '616','blockid' => '28','pageid' => '48','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '617','blockid' => '9','pageid' => '48','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '618','blockid' => '2','pageid' => '48','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '619','blockid' => '7','pageid' => '48','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '620','blockid' => '1','pageid' => '48','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '629','blockid' => '28','pageid' => '49','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '630','blockid' => '9','pageid' => '49','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '631','blockid' => '2','pageid' => '49','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '632','blockid' => '7','pageid' => '49','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '633','blockid' => '1','pageid' => '49','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '642','blockid' => '28','pageid' => '50','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '643','blockid' => '9','pageid' => '50','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '644','blockid' => '2','pageid' => '50','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '645','blockid' => '7','pageid' => '50','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '646','blockid' => '1','pageid' => '50','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '655','blockid' => '28','pageid' => '51','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '656','blockid' => '9','pageid' => '51','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '657','blockid' => '2','pageid' => '51','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '658','blockid' => '7','pageid' => '51','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '659','blockid' => '1','pageid' => '51','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '668','blockid' => '28','pageid' => '52','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '669','blockid' => '9','pageid' => '52','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '670','blockid' => '2','pageid' => '52','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '671','blockid' => '7','pageid' => '52','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '672','blockid' => '1','pageid' => '52','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '681','blockid' => '28','pageid' => '53','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '682','blockid' => '9','pageid' => '53','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '683','blockid' => '2','pageid' => '53','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '684','blockid' => '7','pageid' => '53','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '685','blockid' => '1','pageid' => '53','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '694','blockid' => '28','pageid' => '54','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '695','blockid' => '9','pageid' => '54','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '696','blockid' => '2','pageid' => '54','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '697','blockid' => '7','pageid' => '54','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '698','blockid' => '1','pageid' => '54','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '707','blockid' => '28','pageid' => '55','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '708','blockid' => '9','pageid' => '55','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '709','blockid' => '2','pageid' => '55','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '710','blockid' => '7','pageid' => '55','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '711','blockid' => '1','pageid' => '55','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '720','blockid' => '28','pageid' => '56','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '721','blockid' => '9','pageid' => '56','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '722','blockid' => '2','pageid' => '56','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '723','blockid' => '7','pageid' => '56','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '724','blockid' => '1','pageid' => '56','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '746','blockid' => '28','pageid' => '58','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '747','blockid' => '9','pageid' => '58','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '748','blockid' => '2','pageid' => '58','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '749','blockid' => '7','pageid' => '58','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '750','blockid' => '1','pageid' => '58','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '759','blockid' => '28','pageid' => '59','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '760','blockid' => '9','pageid' => '59','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '761','blockid' => '2','pageid' => '59','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '762','blockid' => '7','pageid' => '59','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '763','blockid' => '1','pageid' => '59','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '772','blockid' => '28','pageid' => '60','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '773','blockid' => '9','pageid' => '60','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '774','blockid' => '2','pageid' => '60','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '775','blockid' => '7','pageid' => '60','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '776','blockid' => '1','pageid' => '60','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '785','blockid' => '28','pageid' => '61','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '786','blockid' => '9','pageid' => '61','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '787','blockid' => '2','pageid' => '61','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '788','blockid' => '7','pageid' => '61','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '789','blockid' => '1','pageid' => '61','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '798','blockid' => '28','pageid' => '62','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '799','blockid' => '9','pageid' => '62','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '800','blockid' => '2','pageid' => '62','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '801','blockid' => '7','pageid' => '62','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '802','blockid' => '1','pageid' => '62','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '811','blockid' => '28','pageid' => '63','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '812','blockid' => '9','pageid' => '63','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '813','blockid' => '2','pageid' => '63','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '814','blockid' => '7','pageid' => '63','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '815','blockid' => '1','pageid' => '63','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '824','blockid' => '28','pageid' => '64','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '825','blockid' => '9','pageid' => '64','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '826','blockid' => '2','pageid' => '64','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '827','blockid' => '7','pageid' => '64','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '828','blockid' => '1','pageid' => '64','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '837','blockid' => '28','pageid' => '65','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '838','blockid' => '9','pageid' => '65','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '839','blockid' => '2','pageid' => '65','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '840','blockid' => '7','pageid' => '65','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '841','blockid' => '1','pageid' => '65','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '850','blockid' => '28','pageid' => '66','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '851','blockid' => '9','pageid' => '66','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '852','blockid' => '2','pageid' => '66','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '853','blockid' => '7','pageid' => '66','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '854','blockid' => '1','pageid' => '66','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '863','blockid' => '28','pageid' => '67','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '864','blockid' => '9','pageid' => '67','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '865','blockid' => '2','pageid' => '67','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '866','blockid' => '7','pageid' => '67','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '867','blockid' => '1','pageid' => '67','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '877','blockid' => '9','pageid' => '68','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '878','blockid' => '2','pageid' => '68','pagetype' => 'course-view','position' => 'r','weight' => '3','visible' => '1','configdata' => 'Tjs=',),
array('id' => '879','blockid' => '7','pageid' => '68','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '880','blockid' => '1','pageid' => '68','pagetype' => 'course-view','position' => 'r','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '889','blockid' => '28','pageid' => '69','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '890','blockid' => '9','pageid' => '69','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '891','blockid' => '2','pageid' => '69','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '892','blockid' => '7','pageid' => '69','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '893','blockid' => '1','pageid' => '69','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '902','blockid' => '28','pageid' => '70','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '903','blockid' => '9','pageid' => '70','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '904','blockid' => '2','pageid' => '70','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '905','blockid' => '7','pageid' => '70','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '906','blockid' => '1','pageid' => '70','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '915','blockid' => '28','pageid' => '71','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '916','blockid' => '9','pageid' => '71','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '917','blockid' => '2','pageid' => '71','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '918','blockid' => '7','pageid' => '71','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '919','blockid' => '1','pageid' => '71','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '928','blockid' => '28','pageid' => '72','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '929','blockid' => '9','pageid' => '72','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '930','blockid' => '2','pageid' => '72','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '931','blockid' => '7','pageid' => '72','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '932','blockid' => '1','pageid' => '72','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '941','blockid' => '28','pageid' => '73','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '942','blockid' => '9','pageid' => '73','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '943','blockid' => '2','pageid' => '73','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '944','blockid' => '7','pageid' => '73','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '945','blockid' => '1','pageid' => '73','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '954','blockid' => '28','pageid' => '74','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '955','blockid' => '9','pageid' => '74','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '956','blockid' => '2','pageid' => '74','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '957','blockid' => '7','pageid' => '74','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '958','blockid' => '1','pageid' => '74','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '967','blockid' => '28','pageid' => '75','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '968','blockid' => '9','pageid' => '75','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '969','blockid' => '2','pageid' => '75','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '970','blockid' => '7','pageid' => '75','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '971','blockid' => '1','pageid' => '75','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '980','blockid' => '28','pageid' => '76','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '981','blockid' => '9','pageid' => '76','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '982','blockid' => '2','pageid' => '76','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '983','blockid' => '7','pageid' => '76','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '984','blockid' => '1','pageid' => '76','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '993','blockid' => '28','pageid' => '77','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '994','blockid' => '9','pageid' => '77','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '995','blockid' => '2','pageid' => '77','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '996','blockid' => '7','pageid' => '77','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '997','blockid' => '1','pageid' => '77','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1006','blockid' => '28','pageid' => '78','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1007','blockid' => '9','pageid' => '78','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1008','blockid' => '2','pageid' => '78','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1009','blockid' => '7','pageid' => '78','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1010','blockid' => '1','pageid' => '78','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1019','blockid' => '28','pageid' => '79','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1020','blockid' => '9','pageid' => '79','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1021','blockid' => '2','pageid' => '79','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1022','blockid' => '7','pageid' => '79','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1023','blockid' => '1','pageid' => '79','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1032','blockid' => '28','pageid' => '80','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1033','blockid' => '9','pageid' => '80','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1034','blockid' => '2','pageid' => '80','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1035','blockid' => '7','pageid' => '80','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1036','blockid' => '1','pageid' => '80','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1045','blockid' => '28','pageid' => '81','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1046','blockid' => '9','pageid' => '81','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1047','blockid' => '2','pageid' => '81','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1048','blockid' => '7','pageid' => '81','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1049','blockid' => '1','pageid' => '81','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1058','blockid' => '28','pageid' => '82','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1059','blockid' => '9','pageid' => '82','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1060','blockid' => '2','pageid' => '82','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1061','blockid' => '7','pageid' => '82','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1062','blockid' => '1','pageid' => '82','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1071','blockid' => '28','pageid' => '83','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1072','blockid' => '9','pageid' => '83','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1073','blockid' => '2','pageid' => '83','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1074','blockid' => '7','pageid' => '83','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1075','blockid' => '1','pageid' => '83','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1084','blockid' => '28','pageid' => '84','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1085','blockid' => '9','pageid' => '84','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1086','blockid' => '2','pageid' => '84','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1087','blockid' => '7','pageid' => '84','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1088','blockid' => '1','pageid' => '84','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1097','blockid' => '28','pageid' => '85','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1098','blockid' => '9','pageid' => '85','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1099','blockid' => '2','pageid' => '85','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1100','blockid' => '7','pageid' => '85','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1101','blockid' => '1','pageid' => '85','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1110','blockid' => '28','pageid' => '86','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1111','blockid' => '9','pageid' => '86','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1112','blockid' => '2','pageid' => '86','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1113','blockid' => '7','pageid' => '86','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1114','blockid' => '1','pageid' => '86','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1123','blockid' => '28','pageid' => '87','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1124','blockid' => '9','pageid' => '87','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1125','blockid' => '2','pageid' => '87','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1126','blockid' => '7','pageid' => '87','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1127','blockid' => '1','pageid' => '87','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1136','blockid' => '28','pageid' => '88','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1137','blockid' => '9','pageid' => '88','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1138','blockid' => '2','pageid' => '88','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1139','blockid' => '7','pageid' => '88','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1140','blockid' => '1','pageid' => '88','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1149','blockid' => '28','pageid' => '89','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1150','blockid' => '9','pageid' => '89','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1151','blockid' => '2','pageid' => '89','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1152','blockid' => '7','pageid' => '89','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1153','blockid' => '1','pageid' => '89','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1162','blockid' => '28','pageid' => '90','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1163','blockid' => '9','pageid' => '90','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1164','blockid' => '2','pageid' => '90','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1165','blockid' => '7','pageid' => '90','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1166','blockid' => '1','pageid' => '90','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1175','blockid' => '28','pageid' => '91','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1176','blockid' => '9','pageid' => '91','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1177','blockid' => '2','pageid' => '91','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1178','blockid' => '7','pageid' => '91','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1179','blockid' => '1','pageid' => '91','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1188','blockid' => '28','pageid' => '92','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1189','blockid' => '9','pageid' => '92','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1190','blockid' => '2','pageid' => '92','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1191','blockid' => '7','pageid' => '92','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1192','blockid' => '1','pageid' => '92','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1201','blockid' => '28','pageid' => '93','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1202','blockid' => '9','pageid' => '93','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1203','blockid' => '2','pageid' => '93','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1204','blockid' => '7','pageid' => '93','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1205','blockid' => '1','pageid' => '93','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1214','blockid' => '28','pageid' => '94','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1215','blockid' => '9','pageid' => '94','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1216','blockid' => '2','pageid' => '94','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1217','blockid' => '7','pageid' => '94','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1218','blockid' => '1','pageid' => '94','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1227','blockid' => '28','pageid' => '95','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1228','blockid' => '9','pageid' => '95','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1229','blockid' => '2','pageid' => '95','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1230','blockid' => '7','pageid' => '95','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1231','blockid' => '1','pageid' => '95','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1240','blockid' => '28','pageid' => '96','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1241','blockid' => '9','pageid' => '96','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1242','blockid' => '2','pageid' => '96','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1243','blockid' => '7','pageid' => '96','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1244','blockid' => '1','pageid' => '96','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1253','blockid' => '28','pageid' => '97','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1254','blockid' => '9','pageid' => '97','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1255','blockid' => '2','pageid' => '97','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1256','blockid' => '7','pageid' => '97','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1257','blockid' => '1','pageid' => '97','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1266','blockid' => '28','pageid' => '98','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1267','blockid' => '9','pageid' => '98','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1268','blockid' => '2','pageid' => '98','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1269','blockid' => '7','pageid' => '98','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1270','blockid' => '1','pageid' => '98','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1279','blockid' => '28','pageid' => '99','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1280','blockid' => '9','pageid' => '99','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1281','blockid' => '2','pageid' => '99','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1282','blockid' => '7','pageid' => '99','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1283','blockid' => '1','pageid' => '99','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1292','blockid' => '28','pageid' => '100','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1293','blockid' => '9','pageid' => '100','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1294','blockid' => '2','pageid' => '100','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1295','blockid' => '7','pageid' => '100','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1296','blockid' => '1','pageid' => '100','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1305','blockid' => '28','pageid' => '101','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1306','blockid' => '9','pageid' => '101','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1307','blockid' => '2','pageid' => '101','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1308','blockid' => '7','pageid' => '101','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1309','blockid' => '1','pageid' => '101','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1318','blockid' => '28','pageid' => '102','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1319','blockid' => '9','pageid' => '102','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1320','blockid' => '2','pageid' => '102','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1321','blockid' => '7','pageid' => '102','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1322','blockid' => '1','pageid' => '102','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1331','blockid' => '28','pageid' => '103','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1332','blockid' => '9','pageid' => '103','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1333','blockid' => '2','pageid' => '103','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1334','blockid' => '7','pageid' => '103','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1335','blockid' => '1','pageid' => '103','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1344','blockid' => '28','pageid' => '104','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1345','blockid' => '9','pageid' => '104','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1346','blockid' => '2','pageid' => '104','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1347','blockid' => '7','pageid' => '104','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1348','blockid' => '1','pageid' => '104','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1357','blockid' => '28','pageid' => '105','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1358','blockid' => '9','pageid' => '105','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1359','blockid' => '2','pageid' => '105','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1360','blockid' => '7','pageid' => '105','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1361','blockid' => '1','pageid' => '105','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1370','blockid' => '28','pageid' => '106','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1371','blockid' => '9','pageid' => '106','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1372','blockid' => '2','pageid' => '106','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1373','blockid' => '7','pageid' => '106','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1374','blockid' => '1','pageid' => '106','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1383','blockid' => '28','pageid' => '107','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1384','blockid' => '9','pageid' => '107','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1385','blockid' => '2','pageid' => '107','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1386','blockid' => '7','pageid' => '107','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1387','blockid' => '1','pageid' => '107','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1396','blockid' => '28','pageid' => '108','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1397','blockid' => '9','pageid' => '108','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1398','blockid' => '2','pageid' => '108','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1399','blockid' => '7','pageid' => '108','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1400','blockid' => '1','pageid' => '108','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1409','blockid' => '28','pageid' => '109','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1410','blockid' => '9','pageid' => '109','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1411','blockid' => '2','pageid' => '109','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1412','blockid' => '7','pageid' => '109','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1413','blockid' => '1','pageid' => '109','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1422','blockid' => '28','pageid' => '110','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1423','blockid' => '9','pageid' => '110','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1424','blockid' => '2','pageid' => '110','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1425','blockid' => '7','pageid' => '110','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1426','blockid' => '1','pageid' => '110','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1435','blockid' => '28','pageid' => '111','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1436','blockid' => '9','pageid' => '111','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1437','blockid' => '2','pageid' => '111','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1438','blockid' => '7','pageid' => '111','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1439','blockid' => '1','pageid' => '111','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => 'Tjs=',),
array('id' => '1499','blockid' => '4','pageid' => '0','pagetype' => 'admin','position' => 'l','weight' => '0','visible' => '1','configdata' => '',),
array('id' => '1500','blockid' => '3','pageid' => '0','pagetype' => 'admin','position' => 'l','weight' => '1','visible' => '1','configdata' => '',),
array('id' => '1528','blockid' => '1','pageid' => '121','pagetype' => 'course-view','position' => 'r','weight' => '2','visible' => '1','configdata' => '',),
array('id' => '1530','blockid' => '2','pageid' => '121','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => '',),
array('id' => '1535','blockid' => '7','pageid' => '121','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => '',),
array('id' => '1536','blockid' => '9','pageid' => '121','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => '',),
array('id' => '1748','blockid' => '5','pageid' => '72','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1749','blockid' => '6','pageid' => '72','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '1834','blockid' => '5','pageid' => '6869','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1835','blockid' => '6','pageid' => '6869','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '1919','blockid' => '5','pageid' => '2596','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1920','blockid' => '6','pageid' => '2596','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '1921','blockid' => '5','pageid' => '1687','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1922','blockid' => '6','pageid' => '1687','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '1923','blockid' => '5','pageid' => '2413','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1924','blockid' => '6','pageid' => '2413','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '1925','blockid' => '5','pageid' => '1059','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1926','blockid' => '6','pageid' => '1059','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '1939','blockid' => '5','pageid' => '1103','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '1940','blockid' => '6','pageid' => '1103','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2104','blockid' => '5','pageid' => '1869','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2105','blockid' => '6','pageid' => '1869','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2315','blockid' => '5','pageid' => '15','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2316','blockid' => '6','pageid' => '15','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2317','blockid' => '5','pageid' => '1485','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2318','blockid' => '6','pageid' => '1485','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2319','blockid' => '5','pageid' => '1371','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2320','blockid' => '6','pageid' => '1371','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2321','blockid' => '5','pageid' => '202','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2322','blockid' => '6','pageid' => '202','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2323','blockid' => '5','pageid' => '1146','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2324','blockid' => '6','pageid' => '1146','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2325','blockid' => '5','pageid' => '2198','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2326','blockid' => '6','pageid' => '2198','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2434','blockid' => '28','pageid' => '217','pagetype' => 'course-view','position' => 'l','weight' => '0','visible' => '1','configdata' => '',),
array('id' => '2435','blockid' => '1','pageid' => '217','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => '',),
array('id' => '2436','blockid' => '33','pageid' => '217','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => '',),
array('id' => '2437','blockid' => '2','pageid' => '217','pagetype' => 'course-view','position' => 'l','weight' => '3','visible' => '1','configdata' => '',),
array('id' => '2438','blockid' => '10','pageid' => '217','pagetype' => 'course-view','position' => 'l','weight' => '4','visible' => '1','configdata' => '',),
array('id' => '2439','blockid' => '26','pageid' => '217','pagetype' => 'course-view','position' => 'r','weight' => '0','visible' => '1','configdata' => '',),
array('id' => '2440','blockid' => '8','pageid' => '217','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => '',),
array('id' => '2441','blockid' => '30','pageid' => '217','pagetype' => 'course-view','position' => 'r','weight' => '2','visible' => '1','configdata' => '',),
array('id' => '2442','blockid' => '21','pageid' => '1','pagetype' => 'course-view','position' => 'l','weight' => '1','visible' => '1','configdata' => '',),
array('id' => '2443','blockid' => '22','pageid' => '1','pagetype' => 'course-view','position' => 'l','weight' => '2','visible' => '1','configdata' => '',),
array('id' => '2444','blockid' => '4','pageid' => '1','pagetype' => 'course-view','position' => 'l','weight' => '3','visible' => '1','configdata' => '',),
array('id' => '2445','blockid' => '20','pageid' => '1','pagetype' => 'course-view','position' => 'r','weight' => '5','visible' => '1','configdata' => '',),
array('id' => '2446','blockid' => '7','pageid' => '1','pagetype' => 'course-view','position' => 'r','weight' => '1','visible' => '1','configdata' => '',),
array('id' => '2447','blockid' => '43','pageid' => '1','pagetype' => 'course-view','position' => 'r','weight' => '2','visible' => '1','configdata' => '',),
array('id' => '2448','blockid' => '45','pageid' => '1','pagetype' => 'course-view','position' => 'r','weight' => '3','visible' => '1','configdata' => '',),
array('id' => '2449','blockid' => '5','pageid' => '1292','pagetype' => 'blog-view','position' => 'r','weight' => '0','visible' => '1',),
array('id' => '2450','blockid' => '6','pageid' => '1292','pagetype' => 'blog-view','position' => 'r','weight' => '1','visible' => '1',),
array('id' => '2451','blockid' => '23','pageid' => '1','pagetype' => 'course-view','position' => 'r','weight' => '4','visible' => '1','configdata' => '',),
);
print "\n";print "Inserting ".count($items)." records<br />\n";
$i=1;
foreach($items as $item) {
    if(get_field('block_instance', 'id', 'id', $item['id'])) {
        print "Record with id of {$item['id']} already exists!<br>\n";
        continue;
    }
    $newid = insert_record('block_instance',(object) $item);
    if($newid != $item['id']) {
        if(!set_field('block_instance', 'id', $item['id'], 'id', $newid)) {
            print "Could not change id from $newid to {$item['id']}<br>\n";
            continue;
        }
    }
    // record the highest id in the table
    $maxid = get_field_sql('SELECT '.sql_max('id').' FROM '.$CFG->prefix.'block_instance');
    // make sure sequence is higher than highest ID
    bump_sequence('block_instance', $CFG->prefix, $maxid);
    // print output
    // 1 dot per 10 inserts
    if($i%10==0) {
        print ".";
        flush();
    }
    // new line every 200 dots
    if($i%2000==0) {
        print $i." <br>";
    }
    $i++;
}
print "<br>";

set_config("guestloginbutton", 0);
set_config("langmenu", 0);
set_config("forcelogin", 1);
        