<?php
@raise_memory_limit('392M');
@ini_set('max_execution_time','3000');
print "Loading data for table 'course_modules'<br>";
$items = array(array('id' => '1','course' => '2','module' => '8','instance' => '1','section' => '4','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '2','course' => '3','module' => '8','instance' => '2','section' => '7','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '3','course' => '4','module' => '8','instance' => '3','section' => '10','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '4','course' => '5','module' => '8','instance' => '4','section' => '13','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '5','course' => '6','module' => '8','instance' => '5','section' => '16','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '6','course' => '7','module' => '8','instance' => '6','section' => '19','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '7','course' => '8','module' => '8','instance' => '7','section' => '22','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '8','course' => '9','module' => '8','instance' => '8','section' => '25','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '9','course' => '10','module' => '8','instance' => '9','section' => '28','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '10','course' => '11','module' => '8','instance' => '10','section' => '31','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '11','course' => '12','module' => '8','instance' => '11','section' => '34','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '12','course' => '13','module' => '8','instance' => '12','section' => '37','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '13','course' => '14','module' => '8','instance' => '13','section' => '40','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '14','course' => '15','module' => '8','instance' => '14','section' => '43','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '15','course' => '16','module' => '8','instance' => '15','section' => '46','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '16','course' => '17','module' => '8','instance' => '16','section' => '49','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '18','course' => '19','module' => '8','instance' => '18','section' => '55','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '19','course' => '20','module' => '8','instance' => '19','section' => '58','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '20','course' => '21','module' => '8','instance' => '20','section' => '61','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '21','course' => '22','module' => '8','instance' => '21','section' => '64','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '22','course' => '23','module' => '8','instance' => '22','section' => '67','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '23','course' => '24','module' => '8','instance' => '23','section' => '70','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '24','course' => '25','module' => '8','instance' => '24','section' => '73','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '25','course' => '26','module' => '8','instance' => '25','section' => '76','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '26','course' => '27','module' => '8','instance' => '26','section' => '79','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '27','course' => '28','module' => '8','instance' => '27','section' => '82','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '28','course' => '29','module' => '8','instance' => '28','section' => '85','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '29','course' => '30','module' => '8','instance' => '29','section' => '88','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '30','course' => '31','module' => '8','instance' => '30','section' => '91','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '31','course' => '32','module' => '8','instance' => '31','section' => '94','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '32','course' => '33','module' => '8','instance' => '32','section' => '97','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '33','course' => '34','module' => '8','instance' => '33','section' => '100','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '34','course' => '35','module' => '8','instance' => '34','section' => '103','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '35','course' => '36','module' => '8','instance' => '35','section' => '106','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '36','course' => '37','module' => '8','instance' => '36','section' => '109','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '37','course' => '38','module' => '8','instance' => '37','section' => '112','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '38','course' => '39','module' => '8','instance' => '38','section' => '115','added' => '1263422886','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '39','course' => '40','module' => '8','instance' => '39','section' => '118','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '40','course' => '41','module' => '8','instance' => '40','section' => '121','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '41','course' => '42','module' => '8','instance' => '41','section' => '124','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '42','course' => '43','module' => '8','instance' => '42','section' => '127','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '43','course' => '44','module' => '8','instance' => '43','section' => '130','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '44','course' => '45','module' => '8','instance' => '44','section' => '133','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '45','course' => '46','module' => '8','instance' => '45','section' => '136','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '46','course' => '47','module' => '8','instance' => '46','section' => '139','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '47','course' => '48','module' => '8','instance' => '47','section' => '142','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '48','course' => '49','module' => '8','instance' => '48','section' => '145','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '49','course' => '50','module' => '8','instance' => '49','section' => '148','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '50','course' => '51','module' => '8','instance' => '50','section' => '151','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '51','course' => '52','module' => '8','instance' => '51','section' => '154','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '52','course' => '53','module' => '8','instance' => '52','section' => '157','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '53','course' => '54','module' => '8','instance' => '53','section' => '160','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '54','course' => '55','module' => '8','instance' => '54','section' => '163','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '55','course' => '56','module' => '8','instance' => '55','section' => '166','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '57','course' => '58','module' => '8','instance' => '57','section' => '172','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '58','course' => '59','module' => '8','instance' => '58','section' => '175','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '59','course' => '60','module' => '8','instance' => '59','section' => '178','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '60','course' => '61','module' => '8','instance' => '60','section' => '181','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '61','course' => '62','module' => '8','instance' => '61','section' => '184','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '62','course' => '63','module' => '8','instance' => '62','section' => '187','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '63','course' => '64','module' => '8','instance' => '63','section' => '190','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '64','course' => '65','module' => '8','instance' => '64','section' => '193','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '65','course' => '66','module' => '8','instance' => '65','section' => '196','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '66','course' => '67','module' => '8','instance' => '66','section' => '199','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '67','course' => '68','module' => '8','instance' => '67','section' => '202','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '68','course' => '69','module' => '8','instance' => '68','section' => '205','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '69','course' => '70','module' => '8','instance' => '69','section' => '208','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '70','course' => '71','module' => '8','instance' => '70','section' => '211','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '71','course' => '72','module' => '8','instance' => '71','section' => '214','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '72','course' => '73','module' => '8','instance' => '72','section' => '217','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '73','course' => '74','module' => '8','instance' => '73','section' => '220','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '74','course' => '75','module' => '8','instance' => '74','section' => '223','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '75','course' => '76','module' => '8','instance' => '75','section' => '226','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '76','course' => '77','module' => '8','instance' => '76','section' => '229','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '77','course' => '78','module' => '8','instance' => '77','section' => '232','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '78','course' => '79','module' => '8','instance' => '78','section' => '235','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '79','course' => '80','module' => '8','instance' => '79','section' => '238','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '80','course' => '81','module' => '8','instance' => '80','section' => '241','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '81','course' => '82','module' => '8','instance' => '81','section' => '244','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '82','course' => '83','module' => '8','instance' => '82','section' => '247','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '83','course' => '84','module' => '8','instance' => '83','section' => '250','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '84','course' => '85','module' => '8','instance' => '84','section' => '253','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '85','course' => '86','module' => '8','instance' => '85','section' => '256','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '86','course' => '87','module' => '8','instance' => '86','section' => '259','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '87','course' => '88','module' => '8','instance' => '87','section' => '262','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '88','course' => '89','module' => '8','instance' => '88','section' => '265','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '89','course' => '90','module' => '8','instance' => '89','section' => '268','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '90','course' => '91','module' => '8','instance' => '90','section' => '271','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '91','course' => '92','module' => '8','instance' => '91','section' => '274','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '92','course' => '93','module' => '8','instance' => '92','section' => '277','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '93','course' => '94','module' => '8','instance' => '93','section' => '280','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '94','course' => '95','module' => '8','instance' => '94','section' => '283','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '95','course' => '96','module' => '8','instance' => '95','section' => '286','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '96','course' => '97','module' => '8','instance' => '96','section' => '289','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '97','course' => '98','module' => '8','instance' => '97','section' => '292','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '98','course' => '99','module' => '8','instance' => '98','section' => '295','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '99','course' => '100','module' => '8','instance' => '99','section' => '298','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '100','course' => '101','module' => '8','instance' => '100','section' => '301','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '101','course' => '102','module' => '8','instance' => '101','section' => '304','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '102','course' => '103','module' => '8','instance' => '102','section' => '307','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '103','course' => '104','module' => '8','instance' => '103','section' => '310','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '104','course' => '105','module' => '8','instance' => '104','section' => '313','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '105','course' => '106','module' => '8','instance' => '105','section' => '316','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '106','course' => '107','module' => '8','instance' => '106','section' => '319','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '107','course' => '108','module' => '8','instance' => '107','section' => '322','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '108','course' => '109','module' => '8','instance' => '108','section' => '325','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '109','course' => '110','module' => '8','instance' => '109','section' => '328','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '110','course' => '111','module' => '8','instance' => '110','section' => '331','added' => '1263422844','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '657','course' => '121','module' => '10','instance' => '47','section' => '490','added' => '1263862710','score' => '0','indent' => '0','visible' => '0','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '835','course' => '1','module' => '10','instance' => '84','section' => '574','added' => '1266112437','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '1153','course' => '217','module' => '10','instance' => '164','section' => '768','added' => '1267734304','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '0',),
array('id' => '1154','course' => '217','module' => '8','instance' => '158','section' => '769','idnumber' => '','added' => '1267735577','score' => '0','indent' => '0','visible' => '1','visibleold' => '1','groupmode' => '0','groupingid' => '0','groupmembersonly' => '0','completion' => '2','completiongradeitemnumber' => '0','completionview' => '0','completionexpected' => '0','availablefrom' => '0','availableuntil' => '0','showavailability' => '1',),
);
print "\n";print "Inserting ".count($items)." records<br />\n";
$i=1;
foreach($items as $item) {
    if(get_field('course_modules', 'id', 'id', $item['id'])) {
        print "Record with id of {$item['id']} already exists!<br>\n";
        continue;
    }
    $newid = insert_record('course_modules',(object) $item);
    if($newid != $item['id']) {
        if(!set_field('course_modules', 'id', $item['id'], 'id', $newid)) {
            print "Could not change id from $newid to {$item['id']}<br>\n";
            continue;
        }
    }
    // record the highest id in the table
    $maxid = get_field_sql('SELECT '.sql_max('id').' FROM '.$CFG->prefix.'course_modules');
    // make sure sequence is higher than highest ID
    bump_sequence('course_modules', $CFG->prefix, $maxid);
    // print output
    // 1 dot per 10 inserts
    if($i%10==0) {
        print ".";
        flush();
    }
    // new line every 200 dots
    if($i%2000==0) {
        print $i." <br>";
    }
    $i++;
}
print "<br>";

set_config("guestloginbutton", 0);
set_config("langmenu", 0);
set_config("forcelogin", 1);
        