<?php
@raise_memory_limit('496M');
@ini_set('max_execution_time','3000');
print "Loading data for table 'course_completion_aggr_methd'<br>";
$items = array(array('id' => '1','course' => '2','method' => '1',),
array('id' => '2','course' => '2','criteriatype' => '4','method' => '1',),
array('id' => '3','course' => '2','criteriatype' => '8','method' => '1',),
array('id' => '4','course' => '2','criteriatype' => '7','method' => '1',),
array('id' => '5','course' => '3','method' => '1',),
array('id' => '6','course' => '3','criteriatype' => '4','method' => '1',),
array('id' => '7','course' => '3','criteriatype' => '8','method' => '1',),
array('id' => '8','course' => '3','criteriatype' => '7','method' => '1',),
array('id' => '9','course' => '4','method' => '1',),
array('id' => '10','course' => '4','criteriatype' => '4','method' => '1',),
array('id' => '11','course' => '4','criteriatype' => '8','method' => '1',),
array('id' => '12','course' => '4','criteriatype' => '7','method' => '1',),
array('id' => '13','course' => '5','method' => '1',),
array('id' => '14','course' => '5','criteriatype' => '4','method' => '1',),
array('id' => '15','course' => '5','criteriatype' => '8','method' => '1',),
array('id' => '16','course' => '5','criteriatype' => '7','method' => '1',),
array('id' => '17','course' => '6','method' => '1',),
array('id' => '18','course' => '6','criteriatype' => '4','method' => '1',),
array('id' => '19','course' => '6','criteriatype' => '8','method' => '1',),
array('id' => '20','course' => '6','criteriatype' => '7','method' => '1',),
array('id' => '21','course' => '7','method' => '1',),
array('id' => '22','course' => '7','criteriatype' => '4','method' => '1',),
array('id' => '23','course' => '7','criteriatype' => '8','method' => '1',),
array('id' => '24','course' => '7','criteriatype' => '7','method' => '1',),
array('id' => '25','course' => '8','method' => '1',),
array('id' => '26','course' => '8','criteriatype' => '4','method' => '1',),
array('id' => '27','course' => '8','criteriatype' => '8','method' => '1',),
array('id' => '28','course' => '8','criteriatype' => '7','method' => '1',),
array('id' => '29','course' => '9','method' => '1',),
array('id' => '30','course' => '9','criteriatype' => '4','method' => '1',),
array('id' => '31','course' => '9','criteriatype' => '8','method' => '1',),
array('id' => '32','course' => '9','criteriatype' => '7','method' => '1',),
array('id' => '33','course' => '10','method' => '1',),
array('id' => '34','course' => '10','criteriatype' => '4','method' => '1',),
array('id' => '35','course' => '10','criteriatype' => '8','method' => '1',),
array('id' => '36','course' => '10','criteriatype' => '7','method' => '1',),
array('id' => '37','course' => '11','method' => '1',),
array('id' => '38','course' => '11','criteriatype' => '4','method' => '1',),
array('id' => '39','course' => '11','criteriatype' => '8','method' => '1',),
array('id' => '40','course' => '11','criteriatype' => '7','method' => '1',),
array('id' => '41','course' => '12','method' => '1',),
array('id' => '42','course' => '12','criteriatype' => '4','method' => '1',),
array('id' => '43','course' => '12','criteriatype' => '8','method' => '1',),
array('id' => '44','course' => '12','criteriatype' => '7','method' => '1',),
array('id' => '45','course' => '13','method' => '1',),
array('id' => '46','course' => '13','criteriatype' => '4','method' => '1',),
array('id' => '47','course' => '13','criteriatype' => '8','method' => '1',),
array('id' => '48','course' => '13','criteriatype' => '7','method' => '1',),
array('id' => '49','course' => '14','method' => '1',),
array('id' => '50','course' => '14','criteriatype' => '4','method' => '1',),
array('id' => '51','course' => '14','criteriatype' => '8','method' => '1',),
array('id' => '52','course' => '14','criteriatype' => '7','method' => '1',),
array('id' => '53','course' => '15','method' => '1',),
array('id' => '54','course' => '15','criteriatype' => '4','method' => '1',),
array('id' => '55','course' => '15','criteriatype' => '8','method' => '1',),
array('id' => '56','course' => '15','criteriatype' => '7','method' => '1',),
array('id' => '57','course' => '16','method' => '1',),
array('id' => '58','course' => '16','criteriatype' => '4','method' => '1',),
array('id' => '59','course' => '16','criteriatype' => '8','method' => '1',),
array('id' => '60','course' => '16','criteriatype' => '7','method' => '1',),
array('id' => '61','course' => '17','method' => '1',),
array('id' => '62','course' => '17','criteriatype' => '4','method' => '1',),
array('id' => '63','course' => '17','criteriatype' => '8','method' => '1',),
array('id' => '64','course' => '17','criteriatype' => '7','method' => '1',),
array('id' => '65','course' => '18','method' => '1',),
array('id' => '66','course' => '18','criteriatype' => '4','method' => '1',),
array('id' => '67','course' => '18','criteriatype' => '8','method' => '1',),
array('id' => '68','course' => '18','criteriatype' => '7','method' => '1',),
array('id' => '69','course' => '19','method' => '1',),
array('id' => '70','course' => '19','criteriatype' => '4','method' => '1',),
array('id' => '71','course' => '19','criteriatype' => '8','method' => '1',),
array('id' => '72','course' => '19','criteriatype' => '7','method' => '1',),
array('id' => '73','course' => '20','method' => '1',),
array('id' => '74','course' => '20','criteriatype' => '4','method' => '1',),
array('id' => '75','course' => '20','criteriatype' => '8','method' => '1',),
array('id' => '76','course' => '20','criteriatype' => '7','method' => '1',),
array('id' => '77','course' => '21','method' => '1',),
array('id' => '78','course' => '21','criteriatype' => '4','method' => '1',),
array('id' => '79','course' => '21','criteriatype' => '8','method' => '1',),
array('id' => '80','course' => '21','criteriatype' => '7','method' => '1',),
array('id' => '81','course' => '22','method' => '1',),
array('id' => '82','course' => '22','criteriatype' => '4','method' => '1',),
array('id' => '83','course' => '22','criteriatype' => '8','method' => '1',),
array('id' => '84','course' => '22','criteriatype' => '7','method' => '1',),
array('id' => '85','course' => '23','method' => '1',),
array('id' => '86','course' => '23','criteriatype' => '4','method' => '1',),
array('id' => '87','course' => '23','criteriatype' => '8','method' => '1',),
array('id' => '88','course' => '23','criteriatype' => '7','method' => '1',),
array('id' => '89','course' => '24','method' => '1',),
array('id' => '90','course' => '24','criteriatype' => '4','method' => '1',),
array('id' => '91','course' => '24','criteriatype' => '8','method' => '1',),
array('id' => '92','course' => '24','criteriatype' => '7','method' => '1',),
array('id' => '93','course' => '25','method' => '1',),
array('id' => '94','course' => '25','criteriatype' => '4','method' => '1',),
array('id' => '95','course' => '25','criteriatype' => '8','method' => '1',),
array('id' => '96','course' => '25','criteriatype' => '7','method' => '1',),
array('id' => '97','course' => '26','method' => '1',),
array('id' => '98','course' => '26','criteriatype' => '4','method' => '1',),
array('id' => '99','course' => '26','criteriatype' => '8','method' => '1',),
array('id' => '100','course' => '26','criteriatype' => '7','method' => '1',),
array('id' => '101','course' => '27','method' => '1',),
array('id' => '102','course' => '27','criteriatype' => '4','method' => '1',),
array('id' => '103','course' => '27','criteriatype' => '8','method' => '1',),
array('id' => '104','course' => '27','criteriatype' => '7','method' => '1',),
array('id' => '105','course' => '28','method' => '1',),
array('id' => '106','course' => '28','criteriatype' => '4','method' => '1',),
array('id' => '107','course' => '28','criteriatype' => '8','method' => '1',),
array('id' => '108','course' => '28','criteriatype' => '7','method' => '1',),
array('id' => '109','course' => '29','method' => '1',),
array('id' => '110','course' => '29','criteriatype' => '4','method' => '1',),
array('id' => '111','course' => '29','criteriatype' => '8','method' => '1',),
array('id' => '112','course' => '29','criteriatype' => '7','method' => '1',),
array('id' => '113','course' => '30','method' => '1',),
array('id' => '114','course' => '30','criteriatype' => '4','method' => '1',),
array('id' => '115','course' => '30','criteriatype' => '8','method' => '1',),
array('id' => '116','course' => '30','criteriatype' => '7','method' => '1',),
array('id' => '117','course' => '31','method' => '1',),
array('id' => '118','course' => '31','criteriatype' => '4','method' => '1',),
array('id' => '119','course' => '31','criteriatype' => '8','method' => '1',),
array('id' => '120','course' => '31','criteriatype' => '7','method' => '1',),
array('id' => '121','course' => '32','method' => '1',),
array('id' => '122','course' => '32','criteriatype' => '4','method' => '1',),
array('id' => '123','course' => '32','criteriatype' => '8','method' => '1',),
array('id' => '124','course' => '32','criteriatype' => '7','method' => '1',),
array('id' => '125','course' => '33','method' => '1',),
array('id' => '126','course' => '33','criteriatype' => '4','method' => '1',),
array('id' => '127','course' => '33','criteriatype' => '8','method' => '1',),
array('id' => '128','course' => '33','criteriatype' => '7','method' => '1',),
array('id' => '129','course' => '34','method' => '1',),
array('id' => '130','course' => '34','criteriatype' => '4','method' => '1',),
array('id' => '131','course' => '34','criteriatype' => '8','method' => '1',),
array('id' => '132','course' => '34','criteriatype' => '7','method' => '1',),
array('id' => '133','course' => '35','method' => '1',),
array('id' => '134','course' => '35','criteriatype' => '4','method' => '1',),
array('id' => '135','course' => '35','criteriatype' => '8','method' => '1',),
array('id' => '136','course' => '35','criteriatype' => '7','method' => '1',),
array('id' => '137','course' => '36','method' => '1',),
array('id' => '138','course' => '36','criteriatype' => '4','method' => '1',),
array('id' => '139','course' => '36','criteriatype' => '8','method' => '1',),
array('id' => '140','course' => '36','criteriatype' => '7','method' => '1',),
array('id' => '141','course' => '37','method' => '1',),
array('id' => '142','course' => '37','criteriatype' => '4','method' => '1',),
array('id' => '143','course' => '37','criteriatype' => '8','method' => '1',),
array('id' => '144','course' => '37','criteriatype' => '7','method' => '1',),
array('id' => '145','course' => '38','method' => '1',),
array('id' => '146','course' => '38','criteriatype' => '4','method' => '1',),
array('id' => '147','course' => '38','criteriatype' => '8','method' => '1',),
array('id' => '148','course' => '38','criteriatype' => '7','method' => '1',),
array('id' => '149','course' => '39','method' => '1',),
array('id' => '150','course' => '39','criteriatype' => '4','method' => '1',),
array('id' => '151','course' => '39','criteriatype' => '8','method' => '1',),
array('id' => '152','course' => '39','criteriatype' => '7','method' => '1',),
array('id' => '153','course' => '40','method' => '1',),
array('id' => '154','course' => '40','criteriatype' => '4','method' => '1',),
array('id' => '155','course' => '40','criteriatype' => '8','method' => '1',),
array('id' => '156','course' => '40','criteriatype' => '7','method' => '1',),
array('id' => '157','course' => '41','method' => '1',),
array('id' => '158','course' => '41','criteriatype' => '4','method' => '1',),
array('id' => '159','course' => '41','criteriatype' => '8','method' => '1',),
array('id' => '160','course' => '41','criteriatype' => '7','method' => '1',),
array('id' => '161','course' => '42','method' => '1',),
array('id' => '162','course' => '42','criteriatype' => '4','method' => '1',),
array('id' => '163','course' => '42','criteriatype' => '8','method' => '1',),
array('id' => '164','course' => '42','criteriatype' => '7','method' => '1',),
array('id' => '165','course' => '43','method' => '1',),
array('id' => '166','course' => '43','criteriatype' => '4','method' => '1',),
array('id' => '167','course' => '43','criteriatype' => '8','method' => '1',),
array('id' => '168','course' => '43','criteriatype' => '7','method' => '1',),
array('id' => '169','course' => '44','method' => '1',),
array('id' => '170','course' => '44','criteriatype' => '4','method' => '1',),
array('id' => '171','course' => '44','criteriatype' => '8','method' => '1',),
array('id' => '172','course' => '44','criteriatype' => '7','method' => '1',),
array('id' => '173','course' => '45','method' => '1',),
array('id' => '174','course' => '45','criteriatype' => '4','method' => '1',),
array('id' => '175','course' => '45','criteriatype' => '8','method' => '1',),
array('id' => '176','course' => '45','criteriatype' => '7','method' => '1',),
array('id' => '177','course' => '46','method' => '1',),
array('id' => '178','course' => '46','criteriatype' => '4','method' => '1',),
array('id' => '179','course' => '46','criteriatype' => '8','method' => '1',),
array('id' => '180','course' => '46','criteriatype' => '7','method' => '1',),
array('id' => '181','course' => '47','method' => '1',),
array('id' => '182','course' => '47','criteriatype' => '4','method' => '1',),
array('id' => '183','course' => '47','criteriatype' => '8','method' => '1',),
array('id' => '184','course' => '47','criteriatype' => '7','method' => '1',),
array('id' => '185','course' => '48','method' => '1',),
array('id' => '186','course' => '48','criteriatype' => '4','method' => '1',),
array('id' => '187','course' => '48','criteriatype' => '8','method' => '1',),
array('id' => '188','course' => '48','criteriatype' => '7','method' => '1',),
array('id' => '189','course' => '49','method' => '1',),
array('id' => '190','course' => '49','criteriatype' => '4','method' => '1',),
array('id' => '191','course' => '49','criteriatype' => '8','method' => '1',),
array('id' => '192','course' => '49','criteriatype' => '7','method' => '1',),
array('id' => '193','course' => '50','method' => '1',),
array('id' => '194','course' => '50','criteriatype' => '4','method' => '1',),
array('id' => '195','course' => '50','criteriatype' => '8','method' => '1',),
array('id' => '196','course' => '50','criteriatype' => '7','method' => '1',),
array('id' => '197','course' => '51','method' => '1',),
array('id' => '198','course' => '51','criteriatype' => '4','method' => '1',),
array('id' => '199','course' => '51','criteriatype' => '8','method' => '1',),
array('id' => '200','course' => '51','criteriatype' => '7','method' => '1',),
array('id' => '201','course' => '52','method' => '1',),
array('id' => '202','course' => '52','criteriatype' => '4','method' => '1',),
array('id' => '203','course' => '52','criteriatype' => '8','method' => '1',),
array('id' => '204','course' => '52','criteriatype' => '7','method' => '1',),
array('id' => '205','course' => '53','method' => '1',),
array('id' => '206','course' => '53','criteriatype' => '4','method' => '1',),
array('id' => '207','course' => '53','criteriatype' => '8','method' => '1',),
array('id' => '208','course' => '53','criteriatype' => '7','method' => '1',),
array('id' => '209','course' => '54','method' => '1',),
array('id' => '210','course' => '54','criteriatype' => '4','method' => '1',),
array('id' => '211','course' => '54','criteriatype' => '8','method' => '1',),
array('id' => '212','course' => '54','criteriatype' => '7','method' => '1',),
array('id' => '213','course' => '55','method' => '1',),
array('id' => '214','course' => '55','criteriatype' => '4','method' => '1',),
array('id' => '215','course' => '55','criteriatype' => '8','method' => '1',),
array('id' => '216','course' => '55','criteriatype' => '7','method' => '1',),
array('id' => '217','course' => '56','method' => '1',),
array('id' => '218','course' => '56','criteriatype' => '4','method' => '1',),
array('id' => '219','course' => '56','criteriatype' => '8','method' => '1',),
array('id' => '220','course' => '56','criteriatype' => '7','method' => '1',),
array('id' => '221','course' => '57','method' => '1',),
array('id' => '222','course' => '57','criteriatype' => '4','method' => '1',),
array('id' => '223','course' => '57','criteriatype' => '8','method' => '1',),
array('id' => '224','course' => '57','criteriatype' => '7','method' => '1',),
array('id' => '225','course' => '58','method' => '1',),
array('id' => '226','course' => '58','criteriatype' => '4','method' => '1',),
array('id' => '227','course' => '58','criteriatype' => '8','method' => '1',),
array('id' => '228','course' => '58','criteriatype' => '7','method' => '1',),
array('id' => '229','course' => '59','method' => '1',),
array('id' => '230','course' => '59','criteriatype' => '4','method' => '1',),
array('id' => '231','course' => '59','criteriatype' => '8','method' => '1',),
array('id' => '232','course' => '59','criteriatype' => '7','method' => '1',),
array('id' => '233','course' => '60','method' => '1',),
array('id' => '234','course' => '60','criteriatype' => '4','method' => '1',),
array('id' => '235','course' => '60','criteriatype' => '8','method' => '1',),
array('id' => '236','course' => '60','criteriatype' => '7','method' => '1',),
array('id' => '237','course' => '61','method' => '1',),
array('id' => '238','course' => '61','criteriatype' => '4','method' => '1',),
array('id' => '239','course' => '61','criteriatype' => '8','method' => '1',),
array('id' => '240','course' => '61','criteriatype' => '7','method' => '1',),
array('id' => '241','course' => '62','method' => '1',),
array('id' => '242','course' => '62','criteriatype' => '4','method' => '1',),
array('id' => '243','course' => '62','criteriatype' => '8','method' => '1',),
array('id' => '244','course' => '62','criteriatype' => '7','method' => '1',),
array('id' => '245','course' => '63','method' => '1',),
array('id' => '246','course' => '63','criteriatype' => '4','method' => '1',),
array('id' => '247','course' => '63','criteriatype' => '8','method' => '1',),
array('id' => '248','course' => '63','criteriatype' => '7','method' => '1',),
array('id' => '249','course' => '64','method' => '1',),
array('id' => '250','course' => '64','criteriatype' => '4','method' => '1',),
array('id' => '251','course' => '64','criteriatype' => '8','method' => '1',),
array('id' => '252','course' => '64','criteriatype' => '7','method' => '1',),
array('id' => '253','course' => '65','method' => '1',),
array('id' => '254','course' => '65','criteriatype' => '4','method' => '1',),
array('id' => '255','course' => '65','criteriatype' => '8','method' => '1',),
array('id' => '256','course' => '65','criteriatype' => '7','method' => '1',),
array('id' => '257','course' => '66','method' => '1',),
array('id' => '258','course' => '66','criteriatype' => '4','method' => '1',),
array('id' => '259','course' => '66','criteriatype' => '8','method' => '1',),
array('id' => '260','course' => '66','criteriatype' => '7','method' => '1',),
array('id' => '261','course' => '67','method' => '1',),
array('id' => '262','course' => '67','criteriatype' => '4','method' => '1',),
array('id' => '263','course' => '67','criteriatype' => '8','method' => '1',),
array('id' => '264','course' => '67','criteriatype' => '7','method' => '1',),
array('id' => '265','course' => '68','method' => '1',),
array('id' => '266','course' => '68','criteriatype' => '4','method' => '1',),
array('id' => '267','course' => '68','criteriatype' => '8','method' => '1',),
array('id' => '268','course' => '68','criteriatype' => '7','method' => '1',),
array('id' => '269','course' => '69','method' => '1',),
array('id' => '270','course' => '69','criteriatype' => '4','method' => '1',),
array('id' => '271','course' => '69','criteriatype' => '8','method' => '1',),
array('id' => '272','course' => '69','criteriatype' => '7','method' => '1',),
array('id' => '273','course' => '70','method' => '1',),
array('id' => '274','course' => '70','criteriatype' => '4','method' => '1',),
array('id' => '275','course' => '70','criteriatype' => '8','method' => '1',),
array('id' => '276','course' => '70','criteriatype' => '7','method' => '1',),
array('id' => '277','course' => '71','method' => '1',),
array('id' => '278','course' => '71','criteriatype' => '4','method' => '1',),
array('id' => '279','course' => '71','criteriatype' => '8','method' => '1',),
array('id' => '280','course' => '71','criteriatype' => '7','method' => '1',),
array('id' => '281','course' => '72','method' => '1',),
array('id' => '282','course' => '72','criteriatype' => '4','method' => '1',),
array('id' => '283','course' => '72','criteriatype' => '8','method' => '1',),
array('id' => '284','course' => '72','criteriatype' => '7','method' => '1',),
array('id' => '285','course' => '73','method' => '1',),
array('id' => '286','course' => '73','criteriatype' => '4','method' => '1',),
array('id' => '287','course' => '73','criteriatype' => '8','method' => '1',),
array('id' => '288','course' => '73','criteriatype' => '7','method' => '1',),
array('id' => '289','course' => '74','method' => '1',),
array('id' => '290','course' => '74','criteriatype' => '4','method' => '1',),
array('id' => '291','course' => '74','criteriatype' => '8','method' => '1',),
array('id' => '292','course' => '74','criteriatype' => '7','method' => '1',),
array('id' => '293','course' => '75','method' => '1',),
array('id' => '294','course' => '75','criteriatype' => '4','method' => '1',),
array('id' => '295','course' => '75','criteriatype' => '8','method' => '1',),
array('id' => '296','course' => '75','criteriatype' => '7','method' => '1',),
array('id' => '297','course' => '76','method' => '1',),
array('id' => '298','course' => '76','criteriatype' => '4','method' => '1',),
array('id' => '299','course' => '76','criteriatype' => '8','method' => '1',),
array('id' => '300','course' => '76','criteriatype' => '7','method' => '1',),
array('id' => '301','course' => '77','method' => '1',),
array('id' => '302','course' => '77','criteriatype' => '4','method' => '1',),
array('id' => '303','course' => '77','criteriatype' => '8','method' => '1',),
array('id' => '304','course' => '77','criteriatype' => '7','method' => '1',),
array('id' => '305','course' => '78','method' => '1',),
array('id' => '306','course' => '78','criteriatype' => '4','method' => '1',),
array('id' => '307','course' => '78','criteriatype' => '8','method' => '1',),
array('id' => '308','course' => '78','criteriatype' => '7','method' => '1',),
array('id' => '309','course' => '79','method' => '1',),
array('id' => '310','course' => '79','criteriatype' => '4','method' => '1',),
array('id' => '311','course' => '79','criteriatype' => '8','method' => '1',),
array('id' => '312','course' => '79','criteriatype' => '7','method' => '1',),
array('id' => '313','course' => '80','method' => '1',),
array('id' => '314','course' => '80','criteriatype' => '4','method' => '1',),
array('id' => '315','course' => '80','criteriatype' => '8','method' => '1',),
array('id' => '316','course' => '80','criteriatype' => '7','method' => '1',),
array('id' => '317','course' => '81','method' => '1',),
array('id' => '318','course' => '81','criteriatype' => '4','method' => '1',),
array('id' => '319','course' => '81','criteriatype' => '8','method' => '1',),
array('id' => '320','course' => '81','criteriatype' => '7','method' => '1',),
array('id' => '321','course' => '82','method' => '1',),
array('id' => '322','course' => '82','criteriatype' => '4','method' => '1',),
array('id' => '323','course' => '82','criteriatype' => '8','method' => '1',),
array('id' => '324','course' => '82','criteriatype' => '7','method' => '1',),
array('id' => '325','course' => '83','method' => '1',),
array('id' => '326','course' => '83','criteriatype' => '4','method' => '1',),
array('id' => '327','course' => '83','criteriatype' => '8','method' => '1',),
array('id' => '328','course' => '83','criteriatype' => '7','method' => '1',),
array('id' => '329','course' => '84','method' => '1',),
array('id' => '330','course' => '84','criteriatype' => '4','method' => '1',),
array('id' => '331','course' => '84','criteriatype' => '8','method' => '1',),
array('id' => '332','course' => '84','criteriatype' => '7','method' => '1',),
array('id' => '333','course' => '85','method' => '1',),
array('id' => '334','course' => '85','criteriatype' => '4','method' => '1',),
array('id' => '335','course' => '85','criteriatype' => '8','method' => '1',),
array('id' => '336','course' => '85','criteriatype' => '7','method' => '1',),
array('id' => '337','course' => '86','method' => '1',),
array('id' => '338','course' => '86','criteriatype' => '4','method' => '1',),
array('id' => '339','course' => '86','criteriatype' => '8','method' => '1',),
array('id' => '340','course' => '86','criteriatype' => '7','method' => '1',),
array('id' => '341','course' => '87','method' => '1',),
array('id' => '342','course' => '87','criteriatype' => '4','method' => '1',),
array('id' => '343','course' => '87','criteriatype' => '8','method' => '1',),
array('id' => '344','course' => '87','criteriatype' => '7','method' => '1',),
array('id' => '345','course' => '88','method' => '1',),
array('id' => '346','course' => '88','criteriatype' => '4','method' => '1',),
array('id' => '347','course' => '88','criteriatype' => '8','method' => '1',),
array('id' => '348','course' => '88','criteriatype' => '7','method' => '1',),
array('id' => '349','course' => '89','method' => '1',),
array('id' => '350','course' => '89','criteriatype' => '4','method' => '1',),
array('id' => '351','course' => '89','criteriatype' => '8','method' => '1',),
array('id' => '352','course' => '89','criteriatype' => '7','method' => '1',),
array('id' => '353','course' => '90','method' => '1',),
array('id' => '354','course' => '90','criteriatype' => '4','method' => '1',),
array('id' => '355','course' => '90','criteriatype' => '8','method' => '1',),
array('id' => '356','course' => '90','criteriatype' => '7','method' => '1',),
array('id' => '357','course' => '91','method' => '1',),
array('id' => '358','course' => '91','criteriatype' => '4','method' => '1',),
array('id' => '359','course' => '91','criteriatype' => '8','method' => '1',),
array('id' => '360','course' => '91','criteriatype' => '7','method' => '1',),
array('id' => '361','course' => '92','method' => '1',),
array('id' => '362','course' => '92','criteriatype' => '4','method' => '1',),
array('id' => '363','course' => '92','criteriatype' => '8','method' => '1',),
array('id' => '364','course' => '92','criteriatype' => '7','method' => '1',),
array('id' => '365','course' => '93','method' => '1',),
array('id' => '366','course' => '93','criteriatype' => '4','method' => '1',),
array('id' => '367','course' => '93','criteriatype' => '8','method' => '1',),
array('id' => '368','course' => '93','criteriatype' => '7','method' => '1',),
array('id' => '369','course' => '94','method' => '1',),
array('id' => '370','course' => '94','criteriatype' => '4','method' => '1',),
array('id' => '371','course' => '94','criteriatype' => '8','method' => '1',),
array('id' => '372','course' => '94','criteriatype' => '7','method' => '1',),
array('id' => '373','course' => '95','method' => '1',),
array('id' => '374','course' => '95','criteriatype' => '4','method' => '1',),
array('id' => '375','course' => '95','criteriatype' => '8','method' => '1',),
array('id' => '376','course' => '95','criteriatype' => '7','method' => '1',),
array('id' => '377','course' => '96','method' => '1',),
array('id' => '378','course' => '96','criteriatype' => '4','method' => '1',),
array('id' => '379','course' => '96','criteriatype' => '8','method' => '1',),
array('id' => '380','course' => '96','criteriatype' => '7','method' => '1',),
array('id' => '381','course' => '97','method' => '1',),
array('id' => '382','course' => '97','criteriatype' => '4','method' => '1',),
array('id' => '383','course' => '97','criteriatype' => '8','method' => '1',),
array('id' => '384','course' => '97','criteriatype' => '7','method' => '1',),
array('id' => '385','course' => '98','method' => '1',),
array('id' => '386','course' => '98','criteriatype' => '4','method' => '1',),
array('id' => '387','course' => '98','criteriatype' => '8','method' => '1',),
array('id' => '388','course' => '98','criteriatype' => '7','method' => '1',),
array('id' => '389','course' => '99','method' => '1',),
array('id' => '390','course' => '99','criteriatype' => '4','method' => '1',),
array('id' => '391','course' => '99','criteriatype' => '8','method' => '1',),
array('id' => '392','course' => '99','criteriatype' => '7','method' => '1',),
array('id' => '393','course' => '100','method' => '1',),
array('id' => '394','course' => '100','criteriatype' => '4','method' => '1',),
array('id' => '395','course' => '100','criteriatype' => '8','method' => '1',),
array('id' => '396','course' => '100','criteriatype' => '7','method' => '1',),
array('id' => '397','course' => '101','method' => '1',),
array('id' => '398','course' => '101','criteriatype' => '4','method' => '1',),
array('id' => '399','course' => '101','criteriatype' => '8','method' => '1',),
array('id' => '400','course' => '101','criteriatype' => '7','method' => '1',),
array('id' => '401','course' => '102','method' => '1',),
array('id' => '402','course' => '102','criteriatype' => '4','method' => '1',),
array('id' => '403','course' => '102','criteriatype' => '8','method' => '1',),
array('id' => '404','course' => '102','criteriatype' => '7','method' => '1',),
array('id' => '405','course' => '103','method' => '1',),
array('id' => '406','course' => '103','criteriatype' => '4','method' => '1',),
array('id' => '407','course' => '103','criteriatype' => '8','method' => '1',),
array('id' => '408','course' => '103','criteriatype' => '7','method' => '1',),
array('id' => '409','course' => '104','method' => '1',),
array('id' => '410','course' => '104','criteriatype' => '4','method' => '1',),
array('id' => '411','course' => '104','criteriatype' => '8','method' => '1',),
array('id' => '412','course' => '104','criteriatype' => '7','method' => '1',),
array('id' => '413','course' => '105','method' => '1',),
array('id' => '414','course' => '105','criteriatype' => '4','method' => '1',),
array('id' => '415','course' => '105','criteriatype' => '8','method' => '1',),
array('id' => '416','course' => '105','criteriatype' => '7','method' => '1',),
array('id' => '417','course' => '106','method' => '1',),
array('id' => '418','course' => '106','criteriatype' => '4','method' => '1',),
array('id' => '419','course' => '106','criteriatype' => '8','method' => '1',),
array('id' => '420','course' => '106','criteriatype' => '7','method' => '1',),
array('id' => '421','course' => '107','method' => '1',),
array('id' => '422','course' => '107','criteriatype' => '4','method' => '1',),
array('id' => '423','course' => '107','criteriatype' => '8','method' => '1',),
array('id' => '424','course' => '107','criteriatype' => '7','method' => '1',),
array('id' => '425','course' => '108','method' => '1',),
array('id' => '426','course' => '108','criteriatype' => '4','method' => '1',),
array('id' => '427','course' => '108','criteriatype' => '8','method' => '1',),
array('id' => '428','course' => '108','criteriatype' => '7','method' => '1',),
array('id' => '429','course' => '109','method' => '1',),
array('id' => '430','course' => '109','criteriatype' => '4','method' => '1',),
array('id' => '431','course' => '109','criteriatype' => '8','method' => '1',),
array('id' => '432','course' => '109','criteriatype' => '7','method' => '1',),
array('id' => '433','course' => '110','method' => '1',),
array('id' => '434','course' => '110','criteriatype' => '4','method' => '1',),
array('id' => '435','course' => '110','criteriatype' => '8','method' => '1',),
array('id' => '436','course' => '110','criteriatype' => '7','method' => '1',),
array('id' => '437','course' => '111','method' => '1',),
array('id' => '438','course' => '111','criteriatype' => '4','method' => '1',),
array('id' => '439','course' => '111','criteriatype' => '8','method' => '1',),
array('id' => '440','course' => '111','criteriatype' => '7','method' => '1',),
array('id' => '445','course' => '145','method' => '1',),
array('id' => '446','course' => '145','criteriatype' => '4','method' => '1',),
array('id' => '447','course' => '145','criteriatype' => '8','method' => '1',),
array('id' => '448','course' => '145','criteriatype' => '7','method' => '1',),
array('id' => '453','course' => '152','method' => '1',),
array('id' => '454','course' => '152','criteriatype' => '4','method' => '1',),
array('id' => '455','course' => '152','criteriatype' => '8','method' => '1',),
array('id' => '456','course' => '152','criteriatype' => '7','method' => '1',),
array('id' => '457','course' => '159','method' => '2',),
array('id' => '458','course' => '159','criteriatype' => '4','method' => '1',),
array('id' => '459','course' => '159','criteriatype' => '8','method' => '1',),
array('id' => '460','course' => '159','criteriatype' => '7','method' => '1',),
array('id' => '461','course' => '156','method' => '1',),
array('id' => '462','course' => '156','criteriatype' => '4','method' => '1',),
array('id' => '463','course' => '156','criteriatype' => '8','method' => '1',),
array('id' => '464','course' => '156','criteriatype' => '7','method' => '1',),
array('id' => '469','course' => '153','method' => '1',),
array('id' => '470','course' => '153','criteriatype' => '4','method' => '1',),
array('id' => '471','course' => '153','criteriatype' => '8','method' => '1',),
array('id' => '472','course' => '153','criteriatype' => '7','method' => '1',),
array('id' => '473','course' => '157','method' => '1',),
array('id' => '474','course' => '157','criteriatype' => '4','method' => '1',),
array('id' => '475','course' => '157','criteriatype' => '8','method' => '1',),
array('id' => '476','course' => '157','criteriatype' => '7','method' => '1',),
array('id' => '477','course' => '151','method' => '1',),
array('id' => '478','course' => '151','criteriatype' => '4','method' => '1',),
array('id' => '479','course' => '151','criteriatype' => '8','method' => '1',),
array('id' => '480','course' => '151','criteriatype' => '7','method' => '1',),
array('id' => '481','course' => '150','method' => '1',),
array('id' => '482','course' => '150','criteriatype' => '4','method' => '1',),
array('id' => '483','course' => '150','criteriatype' => '8','method' => '1',),
array('id' => '484','course' => '150','criteriatype' => '7','method' => '1',),
array('id' => '485','course' => '155','method' => '1',),
array('id' => '486','course' => '155','criteriatype' => '4','method' => '1',),
array('id' => '487','course' => '155','criteriatype' => '8','method' => '1',),
array('id' => '488','course' => '155','criteriatype' => '7','method' => '1',),
array('id' => '489','course' => '161','method' => '1',),
array('id' => '490','course' => '161','criteriatype' => '4','method' => '1',),
array('id' => '491','course' => '161','criteriatype' => '8','method' => '1',),
array('id' => '492','course' => '161','criteriatype' => '7','method' => '1',),
array('id' => '493','course' => '162','method' => '1',),
array('id' => '494','course' => '162','criteriatype' => '4','method' => '1',),
array('id' => '495','course' => '162','criteriatype' => '8','method' => '1',),
array('id' => '496','course' => '162','criteriatype' => '7','method' => '1',),
array('id' => '497','course' => '120','method' => '1',),
array('id' => '498','course' => '120','criteriatype' => '4','method' => '1',),
array('id' => '499','course' => '120','criteriatype' => '8','method' => '1',),
array('id' => '500','course' => '120','criteriatype' => '7','method' => '1',),
array('id' => '501','course' => '217','method' => '1',),
array('id' => '502','course' => '217','criteriatype' => '4','method' => '1',),
array('id' => '503','course' => '217','criteriatype' => '8','method' => '1',),
array('id' => '504','course' => '217','criteriatype' => '7','method' => '1',),
array('id' => '513','course' => '218','method' => '1',),
array('id' => '514','course' => '218','criteriatype' => '4','method' => '1',),
array('id' => '515','course' => '218','criteriatype' => '8','method' => '1',),
array('id' => '516','course' => '218','criteriatype' => '7','method' => '1',),
);
print "\n";print "Inserting ".count($items)." records<br />\n";
$i=1;
foreach($items as $item) {
    if(get_field('course_completion_aggr_methd', 'id', 'id', $item['id'])) {
        print "Record with id of {$item['id']} already exists!<br>\n";
        continue;
    }
    $newid = insert_record('course_completion_aggr_methd',(object) $item);
    if($newid != $item['id']) {
        if(!set_field('course_completion_aggr_methd', 'id', $item['id'], 'id', $newid)) {
            print "Could not change id from $newid to {$item['id']}<br>\n";
            continue;
        }
    }
    // record the highest id in the table
    $maxid = get_field_sql('SELECT '.sql_max('id').' FROM '.$CFG->prefix.'course_completion_aggr_methd');
    // make sure sequence is higher than highest ID
    bump_sequence('course_completion_aggr_methd', $CFG->prefix, $maxid);
    // print output
    // 1 dot per 10 inserts
    if($i%10==0) {
        print ".";
        flush();
    }
    // new line every 200 dots
    if($i%2000==0) {
        print $i." <br>";
    }
    $i++;
}
print "<br>";

set_config("guestloginbutton", 0);
set_config("langmenu", 0);
set_config("forcelogin", 1);
        