<?php
@raise_memory_limit('496M');
@ini_set('max_execution_time','3000');
print "Loading data for table 'course_sections'<br>";
$items = array(array('id' => '1','course' => '1','section' => '1','summary' => '<p><img src=\\\"http://demoprep.totaralms.com/file.php/1/fake_home_page.png\\\" /></p>
<p> </p>
<p>
<style type=\\\"text/css\\\"><!--
.generalbox {
    background:none;
}
--></style>
</p>','sequence' => '','visible' => '1',),
array('id' => '3','course' => '2','section' => '0','summary' => '<h1>Stakeholder Management</h1>','sequence' => '','visible' => '1',),
array('id' => '4','course' => '2','section' => '1','sequence' => '1','visible' => '1',),
array('id' => '6','course' => '3','section' => '0','summary' => '<h1>Business Law</h1>','sequence' => '1163','visible' => '1',),
array('id' => '7','course' => '3','section' => '1','sequence' => '2','visible' => '1',),
array('id' => '9','course' => '4','section' => '0','summary' => '<h1>Budgeting</h1>','sequence' => '1164','visible' => '1',),
array('id' => '10','course' => '4','section' => '1','sequence' => '3','visible' => '1',),
array('id' => '12','course' => '5','section' => '0','summary' => '<h1>Business Skills for New Managers</h1>','sequence' => '1165','visible' => '1',),
array('id' => '13','course' => '5','section' => '1','sequence' => '4','visible' => '1',),
array('id' => '15','course' => '6','section' => '0','summary' => '<h1>Coaching and Mentoring</h1>','sequence' => '','visible' => '1',),
array('id' => '16','course' => '6','section' => '1','sequence' => '5','visible' => '1',),
array('id' => '18','course' => '7','section' => '0','summary' => '<h1>Time Management</h1>','sequence' => '1166','visible' => '1',),
array('id' => '19','course' => '7','section' => '1','sequence' => '6','visible' => '1',),
array('id' => '21','course' => '8','section' => '0','summary' => '<h1>Business Writing Skills</h1>','sequence' => '1167','visible' => '1',),
array('id' => '22','course' => '8','section' => '1','sequence' => '7','visible' => '1',),
array('id' => '24','course' => '9','section' => '0','summary' => '<h1>Rapid Reading for business</h1>','sequence' => '1168','visible' => '1',),
array('id' => '25','course' => '9','section' => '1','sequence' => '8','visible' => '1',),
array('id' => '27','course' => '10','section' => '0','summary' => '<h1>Change Management</h1>','sequence' => '1169','visible' => '1',),
array('id' => '28','course' => '10','section' => '1','sequence' => '9','visible' => '1',),
array('id' => '30','course' => '11','section' => '0','summary' => '<h1>Organisational Behaviour</h1>','sequence' => '','visible' => '1',),
array('id' => '31','course' => '11','section' => '1','sequence' => '10','visible' => '1',),
array('id' => '33','course' => '12','section' => '0','summary' => '<h1>Facilitation</h1>','sequence' => '1170','visible' => '1',),
array('id' => '34','course' => '12','section' => '1','sequence' => '11','visible' => '1',),
array('id' => '36','course' => '13','section' => '0','summary' => '<h1>Hospitality</h1>','sequence' => '1171','visible' => '1',),
array('id' => '37','course' => '13','section' => '1','sequence' => '12','visible' => '1',),
array('id' => '39','course' => '14','section' => '0','summary' => '<h1>Supply Chain Management</h1>','sequence' => '1172','visible' => '1',),
array('id' => '40','course' => '14','section' => '1','sequence' => '13','visible' => '1',),
array('id' => '42','course' => '15','section' => '0','summary' => '<h1>Advanced Strategic Planning</h1>','sequence' => '1173','visible' => '1',),
array('id' => '43','course' => '15','section' => '1','sequence' => '14','visible' => '1',),
array('id' => '45','course' => '16','section' => '0','summary' => '<h1>Leading Strategically</h1>','sequence' => '1174','visible' => '1',),
array('id' => '46','course' => '16','section' => '1','sequence' => '15','visible' => '1',),
array('id' => '48','course' => '17','section' => '0','summary' => '<h1>Emotional Intelligence</h1>','sequence' => '1175','visible' => '1',),
array('id' => '49','course' => '17','section' => '1','sequence' => '16','visible' => '1',),
array('id' => '54','course' => '19','section' => '0','summary' => '<h1>Advanced Accounting</h1>','sequence' => '1176','visible' => '1',),
array('id' => '55','course' => '19','section' => '1','sequence' => '18','visible' => '1',),
array('id' => '57','course' => '20','section' => '0','summary' => '<h1>Key Account Management</h1>','sequence' => '1177','visible' => '1',),
array('id' => '58','course' => '20','section' => '1','sequence' => '19','visible' => '1',),
array('id' => '60','course' => '21','section' => '0','summary' => '<h1>Risk Management</h1>','sequence' => '1178','visible' => '1',),
array('id' => '61','course' => '21','section' => '1','sequence' => '20','visible' => '1',),
array('id' => '63','course' => '22','section' => '0','summary' => '<h1>Knowing My Computer (Refresher)</h1>','sequence' => '1157','visible' => '1',),
array('id' => '64','course' => '22','section' => '1','sequence' => '21','visible' => '1',),
array('id' => '66','course' => '23','section' => '0','summary' => '<h1>Reducing Working Capital</h1>','sequence' => '1179','visible' => '1',),
array('id' => '67','course' => '23','section' => '1','sequence' => '22','visible' => '1',),
array('id' => '69','course' => '24','section' => '0','summary' => '<h1>Human Centered Design</h1>','sequence' => '1180','visible' => '1',),
array('id' => '70','course' => '24','section' => '1','sequence' => '23','visible' => '1',),
array('id' => '72','course' => '25','section' => '0','summary' => '<h1>Law of Business Entities</h1>','sequence' => '1181','visible' => '1',),
array('id' => '73','course' => '25','section' => '1','sequence' => '24','visible' => '1',),
array('id' => '75','course' => '26','section' => '0','summary' => '<h1>Forecasting, Budgeting and Strategic Planning</h1>','sequence' => '1182','visible' => '1',),
array('id' => '76','course' => '26','section' => '1','sequence' => '25','visible' => '1',),
array('id' => '78','course' => '27','section' => '0','summary' => '<h1>Knowledge Management</h1>','sequence' => '1183','visible' => '1',),
array('id' => '79','course' => '27','section' => '1','sequence' => '26','visible' => '1',),
array('id' => '81','course' => '28','section' => '0','summary' => '<h1>Company Valuations</h1>','sequence' => '1184','visible' => '1',),
array('id' => '82','course' => '28','section' => '1','sequence' => '27','visible' => '1',),
array('id' => '84','course' => '29','section' => '0','summary' => '<h1>Public Relations</h1>','sequence' => '','visible' => '1',),
array('id' => '85','course' => '29','section' => '1','sequence' => '28','visible' => '1',),
array('id' => '87','course' => '30','section' => '0','summary' => '<h1>Better Communications</h1>','sequence' => '1185','visible' => '1',),
array('id' => '88','course' => '30','section' => '1','sequence' => '29','visible' => '1',),
array('id' => '90','course' => '31','section' => '0','summary' => '<h1>New Product Development</h1>','sequence' => '','visible' => '1',),
array('id' => '91','course' => '31','section' => '1','sequence' => '30','visible' => '1',),
array('id' => '93','course' => '32','section' => '0','summary' => '<h1>Contract Tendering</h1>','sequence' => '1186','visible' => '1',),
array('id' => '94','course' => '32','section' => '1','sequence' => '31','visible' => '1',),
array('id' => '96','course' => '33','section' => '0','summary' => '<h1>Conflict Management</h1>','sequence' => '1160','visible' => '1',),
array('id' => '97','course' => '33','section' => '1','sequence' => '32','visible' => '1',),
array('id' => '99','course' => '34','section' => '0','summary' => '<h1>Managing Information Technology Projects</h1>','sequence' => '1187','visible' => '1',),
array('id' => '100','course' => '34','section' => '1','sequence' => '33','visible' => '1',),
array('id' => '102','course' => '35','section' => '0','summary' => '<h1>Systematic Problem Solving</h1>','sequence' => '','visible' => '1',),
array('id' => '103','course' => '35','section' => '1','sequence' => '34','visible' => '1',),
array('id' => '105','course' => '36','section' => '0','summary' => '<h1>Sales and Marketing</h1>','sequence' => '1188','visible' => '1',),
array('id' => '106','course' => '36','section' => '1','sequence' => '35','visible' => '1',),
array('id' => '108','course' => '37','section' => '0','summary' => '<h1>Business Strategy</h1>','sequence' => '','visible' => '1',),
array('id' => '109','course' => '37','section' => '1','sequence' => '36','visible' => '1',),
array('id' => '111','course' => '38','section' => '0','summary' => '<h1>Communication Theory and Concepts</h1>','sequence' => '1189','visible' => '1',),
array('id' => '112','course' => '38','section' => '1','sequence' => '37','visible' => '1',),
array('id' => '114','course' => '39','section' => '0','summary' => '<h1>Buyer Behaviour</h1>','sequence' => '1190,1250','visible' => '1',),
array('id' => '115','course' => '39','section' => '1','sequence' => '38','visible' => '1',),
array('id' => '117','course' => '40','section' => '0','summary' => '<h1>Marketing Planning</h1>','sequence' => '1191','visible' => '1',),
array('id' => '118','course' => '40','section' => '1','sequence' => '39','visible' => '1',),
array('id' => '120','course' => '41','section' => '0','summary' => '<h1>Assertiveness Skills</h1>','sequence' => '1192','visible' => '1',),
array('id' => '121','course' => '41','section' => '1','sequence' => '40','visible' => '1',),
array('id' => '123','course' => '42','section' => '0','summary' => '<h1>Effective Meetings</h1>','sequence' => '1193','visible' => '1',),
array('id' => '124','course' => '42','section' => '1','sequence' => '41','visible' => '1',),
array('id' => '126','course' => '43','section' => '0','summary' => '<h1>Managing Resources</h1>','sequence' => '1194','visible' => '1',),
array('id' => '127','course' => '43','section' => '1','sequence' => '42','visible' => '1',),
array('id' => '129','course' => '44','section' => '0','summary' => '<h1>Event Planning</h1>','sequence' => '1195','visible' => '1',),
array('id' => '130','course' => '44','section' => '1','sequence' => '43','visible' => '1',),
array('id' => '132','course' => '45','section' => '0','summary' => '<h1>Web Conferencing</h1>','sequence' => '1155','visible' => '1',),
array('id' => '133','course' => '45','section' => '1','sequence' => '44','visible' => '1',),
array('id' => '135','course' => '46','section' => '0','summary' => '<h1>Advanced Business Process Improvement</h1>','sequence' => '1196','visible' => '1',),
array('id' => '136','course' => '46','section' => '1','sequence' => '45','visible' => '1',),
array('id' => '138','course' => '47','section' => '0','summary' => '<h1>Introduction to Banking and Financial Services</h1>','sequence' => '1197','visible' => '1',),
array('id' => '139','course' => '47','section' => '1','sequence' => '46','visible' => '1',),
array('id' => '141','course' => '48','section' => '0','summary' => '<h1>Mind Mapping</h1>','sequence' => '1198','visible' => '1',),
array('id' => '142','course' => '48','section' => '1','sequence' => '47','visible' => '1',),
array('id' => '144','course' => '49','section' => '0','summary' => '<h1>Research Methods</h1>','sequence' => '1199','visible' => '1',),
array('id' => '145','course' => '49','section' => '1','sequence' => '48','visible' => '1',),
array('id' => '147','course' => '50','section' => '0','summary' => '<h1>Digital Marketing</h1>','sequence' => '1200','visible' => '1',),
array('id' => '148','course' => '50','section' => '1','sequence' => '49','visible' => '1',),
array('id' => '150','course' => '51','section' => '0','summary' => '<h1>Quality Management</h1>','sequence' => '1201','visible' => '1',),
array('id' => '151','course' => '51','section' => '1','sequence' => '50','visible' => '1',),
array('id' => '153','course' => '52','section' => '0','summary' => '<h1>Finance for Managers</h1>','sequence' => '1202','visible' => '1',),
array('id' => '154','course' => '52','section' => '1','sequence' => '51','visible' => '1',),
array('id' => '156','course' => '53','section' => '0','summary' => '<h1>Business Modelling</h1>','sequence' => '1203','visible' => '1',),
array('id' => '157','course' => '53','section' => '1','sequence' => '52','visible' => '1',),
array('id' => '159','course' => '54','section' => '0','summary' => '<h1>Outsourcing</h1>','sequence' => '','visible' => '1',),
array('id' => '160','course' => '54','section' => '1','sequence' => '53','visible' => '1',),
array('id' => '162','course' => '55','section' => '0','summary' => '<h1>Professional Communication</h1>','sequence' => '1204','visible' => '1',),
array('id' => '163','course' => '55','section' => '1','sequence' => '54','visible' => '1',),
array('id' => '165','course' => '56','section' => '0','summary' => '<h1>Program Management</h1>','sequence' => '','visible' => '1',),
array('id' => '166','course' => '56','section' => '1','sequence' => '55','visible' => '1',),
array('id' => '171','course' => '58','section' => '0','summary' => '<h1>Systems Thinking</h1>','sequence' => '1205','visible' => '1',),
array('id' => '172','course' => '58','section' => '1','sequence' => '57','visible' => '1',),
array('id' => '174','course' => '59','section' => '0','summary' => '<h1>Achieving Success</h1>','sequence' => '1206','visible' => '1',),
array('id' => '175','course' => '59','section' => '1','sequence' => '58','visible' => '1',),
array('id' => '177','course' => '60','section' => '0','summary' => '<h1>Motivation and Leadership</h1>','sequence' => '1207','visible' => '1',),
array('id' => '178','course' => '60','section' => '1','sequence' => '59','visible' => '1',),
array('id' => '180','course' => '61','section' => '0','summary' => '<h1>Intranet Content Editors Training</h1>','sequence' => '1156','visible' => '1',),
array('id' => '181','course' => '61','section' => '1','sequence' => '60','visible' => '1',),
array('id' => '183','course' => '62','section' => '0','summary' => '<h1>Empowering Individuals and Teams</h1>','sequence' => '1208','visible' => '1',),
array('id' => '184','course' => '62','section' => '1','sequence' => '61','visible' => '1',),
array('id' => '186','course' => '63','section' => '0','summary' => '<h1>Portfolio and programme management</h1>','sequence' => '','visible' => '1',),
array('id' => '187','course' => '63','section' => '1','sequence' => '62','visible' => '1',),
array('id' => '189','course' => '64','section' => '0','summary' => '<h1>Business Case Development</h1>','sequence' => '1209','visible' => '1',),
array('id' => '190','course' => '64','section' => '1','sequence' => '63','visible' => '1',),
array('id' => '192','course' => '65','section' => '0','summary' => '<h1>Advertising Practice</h1>','sequence' => '1210','visible' => '1',),
array('id' => '193','course' => '65','section' => '1','sequence' => '64','visible' => '1',),
array('id' => '195','course' => '66','section' => '0','summary' => '<h1>Developing Strengths into Talents</h1>','sequence' => '1211','visible' => '1',),
array('id' => '196','course' => '66','section' => '1','sequence' => '65','visible' => '1',),
array('id' => '198','course' => '67','section' => '0','summary' => '<h1>Advanced Selling Skills</h1>','sequence' => '','visible' => '1',),
array('id' => '199','course' => '67','section' => '1','sequence' => '66','visible' => '1',),
array('id' => '201','course' => '68','section' => '0','summary' => '<h1>Netiquette</h1>','sequence' => '1161','visible' => '1',),
array('id' => '202','course' => '68','section' => '1','sequence' => '67','visible' => '1',),
array('id' => '204','course' => '69','section' => '0','summary' => '<h1>Pricing Strategies and Tactics</h1>','sequence' => '1212','visible' => '1',),
array('id' => '205','course' => '69','section' => '1','sequence' => '68','visible' => '1',),
array('id' => '207','course' => '70','section' => '0','summary' => '<h1>Value Stream Mapping</h1>','sequence' => '1162','visible' => '1',),
array('id' => '208','course' => '70','section' => '1','sequence' => '69','visible' => '1',),
array('id' => '210','course' => '71','section' => '0','summary' => '<h1>Finance for the Public Sector</h1>','sequence' => '1213','visible' => '1',),
array('id' => '211','course' => '71','section' => '1','sequence' => '70','visible' => '1',),
array('id' => '213','course' => '72','section' => '0','summary' => '<h1>Myers-Briggs for Personal Development</h1>','sequence' => '1214','visible' => '1',),
array('id' => '214','course' => '72','section' => '1','sequence' => '71','visible' => '1',),
array('id' => '216','course' => '73','section' => '0','summary' => '<h1>Service Level Agreements</h1>','sequence' => '1215','visible' => '1',),
array('id' => '217','course' => '73','section' => '1','sequence' => '72','visible' => '1',),
array('id' => '219','course' => '74','section' => '0','summary' => '<h1>Generating Sustainable Revenue Streams</h1>','sequence' => '1216','visible' => '1',),
array('id' => '220','course' => '74','section' => '1','sequence' => '73','visible' => '1',),
array('id' => '222','course' => '75','section' => '0','summary' => '<h1>Data Analysis</h1>','sequence' => '1217','visible' => '1',),
array('id' => '223','course' => '75','section' => '1','sequence' => '74','visible' => '1',),
array('id' => '225','course' => '76','section' => '0','summary' => '<h1>Critical Thinking</h1>','sequence' => '1218','visible' => '1',),
array('id' => '226','course' => '76','section' => '1','sequence' => '75','visible' => '1',),
array('id' => '228','course' => '77','section' => '0','summary' => '<h1>Touch Typing</h1>','sequence' => '1219','visible' => '1',),
array('id' => '229','course' => '77','section' => '1','sequence' => '76','visible' => '1',),
array('id' => '231','course' => '78','section' => '0','summary' => '<h1>Media Training</h1>','sequence' => '1220','visible' => '1',),
array('id' => '232','course' => '78','section' => '1','sequence' => '77','visible' => '1',),
array('id' => '234','course' => '79','section' => '0','summary' => '<h1>Economics</h1>','sequence' => '1221','visible' => '1',),
array('id' => '235','course' => '79','section' => '1','sequence' => '78','visible' => '1',),
array('id' => '237','course' => '80','section' => '0','summary' => '<h1>Inventory Management</h1>','sequence' => '1222','visible' => '1',),
array('id' => '238','course' => '80','section' => '1','sequence' => '79','visible' => '1',),
array('id' => '240','course' => '81','section' => '0','summary' => '<h1>International Marketing</h1>','sequence' => '1223','visible' => '1',),
array('id' => '241','course' => '81','section' => '1','sequence' => '80','visible' => '1',),
array('id' => '243','course' => '82','section' => '0','summary' => '<h1>Technical Writing</h1>','sequence' => '1224','visible' => '1',),
array('id' => '244','course' => '82','section' => '1','sequence' => '81','visible' => '1',),
array('id' => '246','course' => '83','section' => '0','summary' => '<h1>Team Management</h1>','sequence' => '1225','visible' => '1',),
array('id' => '247','course' => '83','section' => '1','sequence' => '82','visible' => '1',),
array('id' => '249','course' => '84','section' => '0','summary' => '<h1>Writing Contracts</h1>','sequence' => '1226','visible' => '1',),
array('id' => '250','course' => '84','section' => '1','sequence' => '83','visible' => '1',),
array('id' => '252','course' => '85','section' => '0','summary' => '<h1>Business Analysis</h1>','sequence' => '1227','visible' => '1',),
array('id' => '253','course' => '85','section' => '1','sequence' => '84','visible' => '1',),
array('id' => '255','course' => '86','section' => '0','summary' => '<h1>Advanced Project Management</h1>','sequence' => '1228','visible' => '1',),
array('id' => '256','course' => '86','section' => '1','sequence' => '85','visible' => '1',),
array('id' => '258','course' => '87','section' => '0','summary' => '<h1>Principles of Managerial Finance</h1>','sequence' => '1229','visible' => '1',),
array('id' => '259','course' => '87','section' => '1','sequence' => '86','visible' => '1',),
array('id' => '261','course' => '88','section' => '0','summary' => '<h1>Business Administration</h1>','sequence' => '','visible' => '1',),
array('id' => '262','course' => '88','section' => '1','sequence' => '87','visible' => '1',),
array('id' => '264','course' => '89','section' => '0','summary' => '<h1>Finance</h1>','sequence' => '1230','visible' => '1',),
array('id' => '265','course' => '89','section' => '1','sequence' => '88','visible' => '1',),
array('id' => '267','course' => '90','section' => '0','summary' => '<h1>Tax Law</h1>','sequence' => '1231','visible' => '1',),
array('id' => '268','course' => '90','section' => '1','sequence' => '89','visible' => '1',),
array('id' => '270','course' => '91','section' => '0','summary' => '<h1>International business</h1>','sequence' => '1232','visible' => '1',),
array('id' => '271','course' => '91','section' => '1','sequence' => '90','visible' => '1',),
array('id' => '273','course' => '92','section' => '0','summary' => '<h1>Basic Accounting</h1>','sequence' => '1233','visible' => '1',),
array('id' => '274','course' => '92','section' => '1','sequence' => '91','visible' => '1',),
array('id' => '276','course' => '93','section' => '0','summary' => '<h1>Creativity and Innovation</h1>','sequence' => '1234','visible' => '1',),
array('id' => '277','course' => '93','section' => '1','sequence' => '92','visible' => '1',),
array('id' => '279','course' => '94','section' => '0','summary' => '<h1>Negotiating Contracts</h1>','sequence' => '','visible' => '1',),
array('id' => '280','course' => '94','section' => '1','sequence' => '93','visible' => '1',),
array('id' => '282','course' => '95','section' => '0','summary' => '<h1>Human Resources</h1>','sequence' => '1235','visible' => '1',),
array('id' => '283','course' => '95','section' => '1','sequence' => '94','visible' => '1',),
array('id' => '285','course' => '96','section' => '0','summary' => '<h1>Building Rapport and Trust</h1>','sequence' => '1236','visible' => '1',),
array('id' => '286','course' => '96','section' => '1','sequence' => '95','visible' => '1',),
array('id' => '288','course' => '97','section' => '0','summary' => '<h1>Strategic Marketing</h1>','sequence' => '1237','visible' => '1',),
array('id' => '289','course' => '97','section' => '1','sequence' => '96','visible' => '1',),
array('id' => '291','course' => '98','section' => '0','summary' => '<h1>Obtaining Feedback</h1>','sequence' => '1238','visible' => '1',),
array('id' => '292','course' => '98','section' => '1','sequence' => '97','visible' => '1',),
array('id' => '294','course' => '99','section' => '0','summary' => '<h1>Event Management</h1>','sequence' => '1239','visible' => '1',),
array('id' => '295','course' => '99','section' => '1','sequence' => '98','visible' => '1',),
array('id' => '297','course' => '100','section' => '0','summary' => '<h1>Writing Reports</h1>','sequence' => '1240','visible' => '1',),
array('id' => '298','course' => '100','section' => '1','sequence' => '99','visible' => '1',),
array('id' => '300','course' => '101','section' => '0','summary' => '<h1>Design Led Thinking</h1>','sequence' => '1241','visible' => '1',),
array('id' => '301','course' => '101','section' => '1','sequence' => '100','visible' => '1',),
array('id' => '303','course' => '102','section' => '0','summary' => '<h1>Customer Attraction</h1>','sequence' => '1242','visible' => '1',),
array('id' => '304','course' => '102','section' => '1','sequence' => '101','visible' => '1',),
array('id' => '306','course' => '103','section' => '0','summary' => '<h1>Procurement Management</h1>','sequence' => '1243','visible' => '1',),
array('id' => '307','course' => '103','section' => '1','sequence' => '102','visible' => '1',),
array('id' => '309','course' => '104','section' => '0','summary' => '<h1>Basic Project Management</h1>','sequence' => '1244','visible' => '1',),
array('id' => '310','course' => '104','section' => '1','sequence' => '103','visible' => '1',),
array('id' => '312','course' => '105','section' => '0','summary' => '<h1>The Business Environment</h1>','sequence' => '1245','visible' => '1',),
array('id' => '313','course' => '105','section' => '1','sequence' => '104','visible' => '1',),
array('id' => '315','course' => '106','section' => '0','summary' => '<h1>Delegation</h1>','sequence' => '1246','visible' => '1',),
array('id' => '316','course' => '106','section' => '1','sequence' => '105','visible' => '1',),
array('id' => '318','course' => '107','section' => '0','summary' => '<h1>Business Computing</h1>','sequence' => '1247','visible' => '1',),
array('id' => '319','course' => '107','section' => '1','sequence' => '106','visible' => '1',),
array('id' => '321','course' => '108','section' => '0','summary' => '<h1>Operations Management</h1>','sequence' => '1159','visible' => '1',),
array('id' => '322','course' => '108','section' => '1','sequence' => '107','visible' => '1',),
array('id' => '324','course' => '109','section' => '0','summary' => '<h1>Sales Skills</h1>','sequence' => '1248','visible' => '1',),
array('id' => '325','course' => '109','section' => '1','sequence' => '108','visible' => '1',),
array('id' => '327','course' => '110','section' => '0','summary' => '<h1>Pay and Performance</h1>','sequence' => '','visible' => '1',),
array('id' => '328','course' => '110','section' => '1','sequence' => '109','visible' => '1',),
array('id' => '330','course' => '111','section' => '0','summary' => '<h1>Creating a successful sales proposal</h1>','sequence' => '','visible' => '1',),
array('id' => '331','course' => '111','section' => '1','sequence' => '110','visible' => '1',),
array('id' => '490','course' => '121','section' => '0','summary' => '<p><span style=\\\"color: #3366ff;\\\"><span style=\\\"font-family: arial,helvetica,sans-serif;\\\"><span style=\\\"font-size: x-large;\\\">Getting Orientated</span></span></span></p>
<p><span style=\\\"font-family: arial,helvetica,sans-serif;\\\"><span style=\\\"font-size: small;\\\">For all new staff and contractors.</span></span></p>
<p><span style=\\\"font-size: small;\\\">This course will help you understand more about the organisation, including what we do, where we\\\'ve come from, how we\\\'re structured, and how we operate. </span></p>
<p> </p>','sequence' => '657,1251,1252','visible' => '1',),
array('id' => '491','course' => '121','section' => '1','summary' => '','sequence' => '','visible' => '1',),
array('id' => '574','course' => '1','section' => '0','summary' => '','sequence' => '835','visible' => '1',),
array('id' => '768','course' => '217','section' => '0','sequence' => '1153,1158','visible' => '1',),
array('id' => '769','course' => '217','section' => '1','summary' => '','sequence' => '1154','visible' => '1',),
array('id' => '770','course' => '218','section' => '0','summary' => '','sequence' => '1262','visible' => '1',),
array('id' => '771','course' => '218','section' => '1','summary' => '','sequence' => '1256,1261','visible' => '1',),
array('id' => '772','course' => '219','section' => '0','sequence' => '1259,1258','visible' => '1',),
array('id' => '773','course' => '219','section' => '1','summary' => '','sequence' => '1260','visible' => '1',),
array('id' => '774','course' => '218','section' => '2','summary' => '','sequence' => '1257,1254','visible' => '1',),
);
print "\n";print "Inserting ".count($items)." records<br />\n";
$i=1;
foreach($items as $item) {
    if(get_field('course_sections', 'id', 'id', $item['id'])) {
        print "Record with id of {$item['id']} already exists!<br>\n";
        continue;
    }
    $newid = insert_record('course_sections',(object) $item);
    if($newid != $item['id']) {
        if(!set_field('course_sections', 'id', $item['id'], 'id', $newid)) {
            print "Could not change id from $newid to {$item['id']}<br>\n";
            continue;
        }
    }
    // record the highest id in the table
    $maxid = get_field_sql('SELECT '.sql_max('id').' FROM '.$CFG->prefix.'course_sections');
    // make sure sequence is higher than highest ID
    bump_sequence('course_sections', $CFG->prefix, $maxid);
    // print output
    // 1 dot per 10 inserts
    if($i%10==0) {
        print ".";
        flush();
    }
    // new line every 200 dots
    if($i%2000==0) {
        print $i." <br>";
    }
    $i++;
}
print "<br>";

set_config("guestloginbutton", 0);
set_config("langmenu", 0);
set_config("forcelogin", 1);
        